/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                // Electric Blue - Primary vibrant color
                electric: {
                    50: '#eff6ff',
                    100: '#dbeafe',
                    200: '#bfdbfe',
                    300: '#93c5fd',
                    400: '#60a5fa',
                    500: '#3b82f6',
                    600: '#2563eb',
                    700: '#1d4ed8',
                    800: '#1e40af',
                    900: '#1e3a8a',
                    950: '#172554',
                },
                // Deep Purple - Secondary vibrant color
                purple: {
                    50: '#faf5ff',
                    100: '#f3e8ff',
                    200: '#e9d5ff',
                    300: '#d8b4fe',
                    400: '#c084fc',
                    500: '#a855f7',
                    600: '#9333ea',
                    700: '#7e22ce',
                    800: '#6b21a8',
                    900: '#581c87',
                    950: '#3b0764',
                },
                // Vibrant Teal - Accent color
                teal: {
                    50: '#f0fdfa',
                    100: '#ccfbf1',
                    200: '#99f6e4',
                    300: '#5eead4',
                    400: '#2dd4bf',
                    500: '#14b8a6',
                    600: '#0d9488',
                    700: '#0f766e',
                    800: '#115e59',
                    900: '#134e4a',
                    950: '#042f2e',
                },
                // Warm Orange - Highlight color
                orange: {
                    50: '#fff7ed',
                    100: '#ffedd5',
                    200: '#fed7aa',
                    300: '#fdba74',
                    400: '#fb923c',
                    500: '#f97316',
                    600: '#ea580c',
                    700: '#c2410c',
                    800: '#9a3412',
                    900: '#7c2d12',
                    950: '#431407',
                },
                // Amber - Gold accent
                amber: {
                    50: '#fffbeb',
                    100: '#fef3c7',
                    200: '#fde68a',
                    300: '#fcd34d',
                    400: '#fbbf24',
                    500: '#f59e0b',
                    600: '#d97706',
                    700: '#b45309',
                    800: '#92400e',
                    900: '#78350f',
                    950: '#451a03',
                },
                // Dark shades for backgrounds
                dark: {
                    50: '#fafafa',
                    100: '#f4f4f5',
                    200: '#e4e4e7',
                    300: '#d4d4d8',
                    400: '#a1a1aa',
                    500: '#71717a',
                    600: '#52525b',
                    700: '#3f3f46',
                    800: '#27272a',
                    900: '#18181b',
                    950: '#09090b',
                },
                // Semantic colors
                success: '#10b981',
                warning: '#f59e0b',
                error: '#ef4444',
                info: '#3b82f6',
            },
            fontFamily: {
                sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
                display: ['Outfit', 'Inter', 'sans-serif'],
                mono: ['JetBrains Mono', 'Consolas', 'monospace'],
            },
            fontSize: {
                'xs': ['0.75rem', { lineHeight: '1rem' }],
                'sm': ['0.875rem', { lineHeight: '1.25rem' }],
                'base': ['1rem', { lineHeight: '1.5rem' }],
                'lg': ['1.125rem', { lineHeight: '1.75rem' }],
                'xl': ['1.25rem', { lineHeight: '1.75rem' }],
                '2xl': ['1.5rem', { lineHeight: '2rem' }],
                '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
                '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
                '5xl': ['3rem', { lineHeight: '1.1' }],
                '6xl': ['3.75rem', { lineHeight: '1' }],
                '7xl': ['4.5rem', { lineHeight: '1' }],
                '8xl': ['6rem', { lineHeight: '1' }],
                '9xl': ['8rem', { lineHeight: '1' }],
            },
            animation: {
                // Existing animations
                'gradient': 'gradient 8s linear infinite',
                'gradient-slow': 'gradient 15s linear infinite',
                'float': 'float 6s ease-in-out infinite',
                'float-slow': 'float 8s ease-in-out infinite',
                'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
                'pulse-glow': 'pulseGlow 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
                'slide-up': 'slideUp 0.5s ease-out',
                'slide-down': 'slideDown 0.5s ease-out',
                'slide-left': 'slideLeft 0.5s ease-out',
                'slide-right': 'slideRight 0.5s ease-out',
                'fade-in': 'fadeIn 0.6s ease-out',
                'fade-in-up': 'fadeInUp 0.6s ease-out',
                'fade-in-down': 'fadeInDown 0.6s ease-out',
                'scale-in': 'scaleIn 0.3s ease-out',
                'scale-in-bounce': 'scaleInBounce 0.5s cubic-bezier(0.68, -0.55, 0.265, 1.55)',
                'shimmer': 'shimmer 2s linear infinite',
                'shimmer-slow': 'shimmer 3s linear infinite',
                'bounce-in': 'bounceIn 0.6s cubic-bezier(0.68, -0.55, 0.265, 1.55)',
                'rotate-in': 'rotateIn 0.6s ease-out',
                'glow': 'glow 2s ease-in-out infinite',
                'spin-slow': 'spin 3s linear infinite',
                // New advanced animations
                'wave': 'wave 3s ease-in-out infinite',
                'bounce-slow': 'bounce 3s infinite',
                'wiggle': 'wiggle 1s ease-in-out infinite',
                'ping-slow': 'ping 2s cubic-bezier(0, 0, 0.2, 1) infinite',
                'gradient-x': 'gradientX 15s ease infinite',
                'gradient-y': 'gradientY 15s ease infinite',
                'gradient-xy': 'gradientXY 15s ease infinite',
                'text-shimmer': 'textShimmer 3s linear infinite',
                'border-glow': 'borderGlow 3s ease-in-out infinite',
            },
            keyframes: {
                gradient: {
                    '0%, 100%': {
                        'background-size': '200% 200%',
                        'background-position': 'left center'
                    },
                    '50%': {
                        'background-size': '200% 200%',
                        'background-position': 'right center'
                    },
                },
                float: {
                    '0%, 100%': { transform: 'translateY(0px)' },
                    '50%': { transform: 'translateY(-20px)' },
                },
                slideUp: {
                    '0%': { transform: 'translateY(100%)', opacity: '0' },
                    '100%': { transform: 'translateY(0)', opacity: '1' },
                },
                slideDown: {
                    '0%': { transform: 'translateY(-100%)', opacity: '0' },
                    '100%': { transform: 'translateY(0)', opacity: '1' },
                },
                slideLeft: {
                    '0%': { transform: 'translateX(100%)', opacity: '0' },
                    '100%': { transform: 'translateX(0)', opacity: '1' },
                },
                slideRight: {
                    '0%': { transform: 'translateX(-100%)', opacity: '0' },
                    '100%': { transform: 'translateX(0)', opacity: '1' },
                },
                fadeIn: {
                    '0%': { opacity: '0' },
                    '100%': { opacity: '1' },
                },
                fadeInUp: {
                    '0%': { opacity: '0', transform: 'translateY(20px)' },
                    '100%': { opacity: '1', transform: 'translateY(0)' },
                },
                fadeInDown: {
                    '0%': { opacity: '0', transform: 'translateY(-20px)' },
                    '100%': { opacity: '1', transform: 'translateY(0)' },
                },
                scaleIn: {
                    '0%': { transform: 'scale(0.9)', opacity: '0' },
                    '100%': { transform: 'scale(1)', opacity: '1' },
                },
                scaleInBounce: {
                    '0%': { transform: 'scale(0.3)', opacity: '0' },
                    '50%': { transform: 'scale(1.05)' },
                    '70%': { transform: 'scale(0.9)' },
                    '100%': { transform: 'scale(1)', opacity: '1' },
                },
                shimmer: {
                    '0%': { backgroundPosition: '-1000px 0' },
                    '100%': { backgroundPosition: '1000px 0' },
                },
                bounceIn: {
                    '0%': { transform: 'scale(0.3)', opacity: '0' },
                    '50%': { transform: 'scale(1.05)' },
                    '70%': { transform: 'scale(0.9)' },
                    '100%': { transform: 'scale(1)', opacity: '1' },
                },
                rotateIn: {
                    '0%': { transform: 'rotate(-200deg) scale(0)', opacity: '0' },
                    '100%': { transform: 'rotate(0) scale(1)', opacity: '1' },
                },
                glow: {
                    '0%, 100%': { boxShadow: '0 0 20px rgba(20, 184, 166, 0.5)' },
                    '50%': { boxShadow: '0 0 40px rgba(20, 184, 166, 0.8)' },
                },
                pulseGlow: {
                    '0%, 100%': { opacity: '1', boxShadow: '0 0 20px rgba(20, 184, 166, 0.4)' },
                    '50%': { opacity: '0.8', boxShadow: '0 0 40px rgba(20, 184, 166, 0.8)' },
                },
                // New keyframes
                wave: {
                    '0%, 100%': { transform: 'rotate(0deg)' },
                    '25%': { transform: 'rotate(5deg)' },
                    '75%': { transform: 'rotate(-5deg)' },
                },
                wiggle: {
                    '0%, 100%': { transform: 'rotate(-3deg)' },
                    '50%': { transform: 'rotate(3deg)' },
                },
                gradientX: {
                    '0%, 100%': { 'background-position': '0% 50%' },
                    '50%': { 'background-position': '100% 50%' },
                },
                gradientY: {
                    '0%, 100%': { 'background-position': '50% 0%' },
                    '50%': { 'background-position': '50% 100%' },
                },
                gradientXY: {
                    '0%, 100%': { 'background-position': '0% 0%' },
                    '25%': { 'background-position': '100% 0%' },
                    '50%': { 'background-position': '100% 100%' },
                    '75%': { 'background-position': '0% 100%' },
                },
                textShimmer: {
                    '0%': { 'background-position': '0% 50%' },
                    '100%': { 'background-position': '200% 50%' },
                },
                borderGlow: {
                    '0%, 100%': { 'border-color': 'rgba(20, 184, 166, 0.3)' },
                    '50%': { 'border-color': 'rgba(20, 184, 166, 1)' },
                },
            },
            backdropBlur: {
                xs: '2px',
            },
            boxShadow: {
                'glass': '0 8px 32px 0 rgba(31, 38, 135, 0.15)',
                'glass-lg': '0 12px 48px 0 rgba(31, 38, 135, 0.2)',
                'soft': '0 2px 8px rgba(0, 0, 0, 0.08)',
                'soft-lg': '0 4px 16px rgba(0, 0, 0, 0.12)',
                'elevation': '0 10px 40px rgba(0, 0, 0, 0.15)',
                'elevation-lg': '0 20px 60px rgba(0, 0, 0, 0.2)',
                'glow-teal': '0 0 20px rgba(20, 184, 166, 0.5)',
                'glow-teal-lg': '0 0 40px rgba(20, 184, 166, 0.6)',
                'glow-blue': '0 0 20px rgba(59, 130, 246, 0.5)',
                'glow-blue-lg': '0 0 40px rgba(59, 130, 246, 0.6)',
                'glow-purple': '0 0 20px rgba(168, 85, 247, 0.5)',
                'glow-purple-lg': '0 0 40px rgba(168, 85, 247, 0.6)',
                'glow-orange': '0 0 20px rgba(249, 115, 22, 0.5)',
                'glow-orange-lg': '0 0 40px rgba(249, 115, 22, 0.6)',
                'glow-amber': '0 0 20px rgba(217, 119, 6, 0.5)',
                'glow-amber-lg': '0 0 40px rgba(217, 119, 6, 0.6)',
                'inner-glow': 'inset 0 0 20px rgba(20, 184, 166, 0.2)',
                'neon': '0 0 5px theme(colors.teal.400), 0 0 20px theme(colors.teal.600)',
                'neon-blue': '0 0 5px theme(colors.electric.400), 0 0 20px theme(colors.electric.600)',
                'neon-purple': '0 0 5px theme(colors.purple.400), 0 0 20px theme(colors.purple.600)',
                'neon-orange': '0 0 5px theme(colors.orange.400), 0 0 20px theme(colors.orange.600)',
            },
            borderRadius: {
                '2xl': '1rem',
                '3xl': '1.5rem',
                '4xl': '2rem',
            },
            backgroundImage: {
                'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
                'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
                // Vibrant gradient meshes
                'gradient-mesh': 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
                'gradient-aurora': 'linear-gradient(135deg, #667eea 0%, #764ba2 50%, #f093fb 100%)',
                'gradient-ocean': 'linear-gradient(135deg, #0d9488 0%, #14b8a6 50%, #2dd4bf 100%)',
                'gradient-sunset': 'linear-gradient(135deg, #f59e0b 0%, #d97706 50%, #dc2626 100%)',
                'gradient-midnight': 'linear-gradient(135deg, #0f172a 0%, #1e293b 50%, #334155 100%)',
                'gradient-electric': 'linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)',
                'gradient-purple': 'linear-gradient(135deg, #a855f7 0%, #7e22ce 100%)',
                'gradient-teal': 'linear-gradient(135deg, #14b8a6 0%, #0d9488 100%)',
                'gradient-orange': 'linear-gradient(135deg, #f97316 0%, #ea580c 100%)',
                'gradient-amber': 'linear-gradient(135deg, #fbbf24 0%, #d97706 100%)',
                'gradient-vibrant': 'linear-gradient(135deg, #3b82f6 0%, #a855f7 50%, #f97316 100%)',
                'gradient-cosmic': 'linear-gradient(135deg, #1e3a8a 0%, #7e22ce 50%, #ea580c 100%)',
                'shimmer-gradient': 'linear-gradient(90deg, transparent, rgba(255,255,255,0.1), transparent)',
                'text-shimmer': 'linear-gradient(90deg, #3b82f6, #a855f7, #f97316, #3b82f6)',
            },
            spacing: {
                '0.5': '0.125rem',
                '1.5': '0.375rem',
                '2.5': '0.625rem',
                '3.5': '0.875rem',
            },
            letterSpacing: {
                'tighter': '-0.05em',
                'tight': '-0.025em',
                'normal': '0',
                'wide': '0.025em',
                'wider': '0.05em',
                'widest': '0.1em',
                'ultra-wide': '0.2em',
            },
            transitionDuration: {
                '0': '0ms',
                '75': '75ms',
                '100': '100ms',
                '150': '150ms',
                '200': '200ms',
                '300': '300ms',
                '500': '500ms',
                '700': '700ms',
                '1000': '1000ms',
            },
        },
    },
    plugins: [],
}
