# Generated by Django 5.0 on 2025-12-21 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city_id", models.IntegerField(unique=True)),
                ("city_name", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "Cities",
                "ordering": ["city_name"],
            },
        ),
        migrations.CreateModel(
            name="Make",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make_id", models.IntegerField(unique=True)),
                ("make_name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["make_name"],
            },
        ),
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_id", models.IntegerField(unique=True)),
                ("part_name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["part_name"],
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_id", models.IntegerField(unique=True)),
                ("state_name", models.CharField(max_length=100)),
                ("state_code", models.CharField(max_length=10)),
            ],
            options={
                "ordering": ["state_name"],
            },
        ),
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_id", models.IntegerField(unique=True)),
                ("model_name", models.CharField(max_length=100)),
                (
                    "make",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="common.make",
                        to_field="make_id",
                    ),
                ),
            ],
            options={
                "ordering": ["model_name"],
            },
        ),
    ]
