# Generated by Django 5.2.8 on 2026-02-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_contactmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="is_read",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
