# Generated by Django 5.0 on 2026-07-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_contactmessage_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('find_business', "Can't find a business"), ('bug', 'Report a bug or issue'), ('suggestion', 'Feature suggestion'), ('general', 'General feedback')], max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('resolved', 'Resolved')], db_index=True, default='unread', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
