# Generated by Django 5.0 on 2026-07-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(db_index=True, help_text="This should be an absolute path, excluding the domain name. Example: '/events/search/'.", max_length=500, unique=True)),
                ('new_path', models.CharField(blank=True, help_text="This can be either an absolute path (as above) or a full URL starting with 'http://'.", max_length=500)),
                ('status_code', models.SmallIntegerField(choices=[(301, '301 - Permanent'), (302, '302 - Temporary')], default=301)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Redirect',
                'verbose_name_plural': 'Redirects',
                'ordering': ['old_path'],
            },
        ),
    ]
