# Generated by Django 5.0 on 2026-10-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_adminnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login', 'User Login'), ('signup', 'User Signup'), ('lead_submit', 'Lead Form Submitted')], db_index=True, max_length=30)),
                ('user_type', models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('admin', 'Admin')], db_index=True, default='customer', max_length=20)),
                ('user_email', models.EmailField(blank=True, help_text='Optional - stored for admin reference', max_length=254, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra context e.g. lead type')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Site Analytics Event',
                'verbose_name_plural': 'Site Analytics Events',
                'ordering': ['-created_at'],
            },
        ),
    ]
