# Generated by Django 5.2.8 on 2026-04-14 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Blog Category",
                "verbose_name_plural": "Blog Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("slug", models.SlugField(blank=True, max_length=350, unique=True)),
                (
                    "excerpt",
                    models.TextField(
                        blank=True,
                        help_text="Short summary shown in listing cards",
                        max_length=500,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Full HTML/rich-text blog content"),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="Hero/thumbnail image URL",
                        max_length=1000,
                    ),
                ),
                ("author", models.CharField(default="JYNM Editorial", max_length=150)),
                ("author_avatar_url", models.URLField(blank=True, max_length=1000)),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, help_text="List of tag strings"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="SEO title (defaults to title)",
                        max_length=300,
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, help_text="SEO meta description", max_length=500
                    ),
                ),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("likes_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="blog.blogcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Post",
                "verbose_name_plural": "Blog Posts",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BlogComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("content", models.TextField()),
                ("is_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="blog.blogpost",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(
                fields=["status", "-published_at"], name="blog_blogpo_status_c0e87f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(
                fields=["is_featured", "status"], name="blog_blogpo_is_feat_eb28c3_idx"
            ),
        ),
    ]
