# Generated by Django 5.1.4 on 2026-06-30 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("bio", models.TextField(blank=True)),
                ("designation", models.CharField(blank=True, max_length=150)),
                ("profile_picture_url", models.URLField(blank=True, max_length=1000)),
                ("website", models.URLField(blank=True, max_length=1000)),
                ("twitter", models.URLField(blank=True, max_length=1000)),
                ("linkedin", models.URLField(blank=True, max_length=1000)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BlogTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="blogcomment",
            name="is_approved",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="author_avatar_url",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="content",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="meta_description",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="meta_title",
        ),
        migrations.AddField(
            model_name="blogcategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subcategories",
                to="blog.blogcategory",
            ),
        ),
        migrations.AddField(
            model_name="blogcomment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("spam", "Spam"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="allow_comments",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="blocks",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Array of JSON block objects for the builder",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="canonical_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="cover_image_url",
            field=models.URLField(
                blank=True, help_text="Hero image URL", max_length=1000
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="is_editors_pick",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="is_trending",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="og_image_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="reading_time",
            field=models.PositiveIntegerField(
                default=5, help_text="Estimated reading time in minutes"
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="related_posts",
            field=models.ManyToManyField(blank=True, to="blog.blogpost"),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="seo_description",
            field=models.CharField(
                blank=True, help_text="SEO meta description", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="seo_title",
            field=models.CharField(
                blank=True, help_text="SEO title (defaults to title)", max_length=300
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="thumbnail_url",
            field=models.URLField(
                blank=True,
                help_text="Card image URL (defaults to cover if blank)",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("scheduled", "Scheduled"),
                    ("archived", "Archived"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="tags",
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="blog.author",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="blog.blogtag"
            ),
        ),
    ]
