"""
Default CMS content — every editable field across the entire website.
Safe to re-run (uses get_or_create).
"""

DEFAULT_CMS_CONTENT = [

    # ══════════════════════════════════════════════════════════════════
    # HOME PAGE
    # ══════════════════════════════════════════════════════════════════

    # Hero Section
    {'page': 'home', 'section': 'hero', 'key': 'heading',
     'label': 'Main Headline (use \\n for line breaks)',
     'value': 'FIND THE JUNKYARD\\nAUTO PARTS YOU NEED —\\nSEARCH IN SECONDS.',
     'content_type': 'text'},
    {'page': 'home', 'section': 'hero', 'key': 'subheading',
     'label': 'Sub-Headline (HTML allowed)',
     'value': 'Locate quality used auto parts from <span style="color: #fb923c; font-weight: 800">verified junkyards</span> near you!',
     'content_type': 'html'},
    {'page': 'home', 'section': 'hero', 'key': 'cta_primary_text',
     'label': 'Primary Button Text',
     'value': 'Browse All Vendors', 'content_type': 'text'},
    {'page': 'home', 'section': 'hero', 'key': 'cta_primary_link',
     'label': 'Primary Button Link',
     'value': '/vendors', 'content_type': 'url'},
    {'page': 'home', 'section': 'hero', 'key': 'cta_secondary_text',
     'label': 'Secondary Button Text',
     'value': 'How It Works', 'content_type': 'text'},
    {'page': 'home', 'section': 'hero', 'key': 'cta_secondary_link',
     'label': 'Secondary Button Link',
     'value': '/how-it-works', 'content_type': 'url'},
    {'page': 'home', 'section': 'hero', 'key': 'trust_badge_1',
     'label': 'Trust Badge 1',
     'value': 'No Spam Guarantee', 'content_type': 'text'},
    {'page': 'home', 'section': 'hero', 'key': 'trust_badge_2',
     'label': 'Trust Badge 2',
     'value': 'Instant Quotes', 'content_type': 'text'},

    # Trust Pillars Section
    {'page': 'home', 'section': 'trust_pillars', 'key': 'badge_label',
     'label': 'Section Badge Text',
     'value': 'Why Trust JYNM', 'content_type': 'text'},
    {'page': 'home', 'section': 'trust_pillars', 'key': 'heading',
     'label': 'Section Heading (HTML allowed)',
     'value': 'Built on <span class="text-blue-600">Reliability</span> & Transparency',
     'content_type': 'html'},
    {'page': 'home', 'section': 'trust_pillars', 'key': 'card1_icon',
     'label': 'Card 1 Icon (emoji)',
     'value': '🔒', 'content_type': 'text'},
    {'page': 'home', 'section': 'trust_pillars', 'key': 'card1_title',
     'label': 'Card 1 Title',
     'value': 'Verified Network', 'content_type': 'text'},
    {'page': 'home', 'section': 'trust_pillars', 'key': 'card1_desc',
     'label': 'Card 1 Description',
     'value': 'Every junkyard is manually vetted. We only list licensed, legitimate salvage yards you can trust.',
     'content_type': 'text'},
    {'page': 'home', 'section': 'trust_pillars', 'key': 'card2_icon',
     'label': 'Card 2 Icon (emoji)',
     'value': '⚡', 'content_type': 'text'},
    {'page': 'home', 'section': 'trust_pillars', 'key': 'card2_title',
     'label': 'Card 2 Title',
     'value': 'Instant Quotes', 'content_type': 'text'},
    {'page': 'home', 'section': 'trust_pillars', 'key': 'card2_desc',
     'label': 'Card 2 Description',
     'value': 'One request reaches multiple vendors simultaneously. Get competitive quotes without the phone tag.',
     'content_type': 'text'},
    {'page': 'home', 'section': 'trust_pillars', 'key': 'card3_icon',
     'label': 'Card 3 Icon (emoji)',
     'value': '🛡', 'content_type': 'text'},
    {'page': 'home', 'section': 'trust_pillars', 'key': 'card3_title',
     'label': 'Card 3 Title',
     'value': 'Zero Spam Promise', 'content_type': 'text'},
    {'page': 'home', 'section': 'trust_pillars', 'key': 'card3_desc',
     'label': 'Card 3 Description',
     'value': 'We never sell your data. Your contact info goes directly and only to the junkyard you choose.',
     'content_type': 'text'},
    {'page': 'home', 'section': 'trust_pillars', 'key': 'card4_icon',
     'label': 'Card 4 Icon (emoji)',
     'value': '💰', 'content_type': 'text'},
    {'page': 'home', 'section': 'trust_pillars', 'key': 'card4_title',
     'label': 'Card 4 Title',
     'value': 'Best Prices Guaranteed', 'content_type': 'text'},
    {'page': 'home', 'section': 'trust_pillars', 'key': 'card4_desc',
     'label': 'Card 4 Description',
     'value': 'Compare hundreds of vendors in seconds. Save up to 80% vs. dealer pricing with real-time availability.',
     'content_type': 'text'},

    # How It Works Section (Home)
    {'page': 'home', 'section': 'how_it_works', 'key': 'heading',
     'label': 'Section Heading (HTML allowed)',
     'value': 'How It <span style="color: #2563eb">Works</span>', 'content_type': 'html'},
    {'page': 'home', 'section': 'how_it_works', 'key': 'subheading',
     'label': 'Section Subheading',
     'value': 'Three simple steps to find the exact used auto parts you need at the best price.',
     'content_type': 'text'},
    {'page': 'home', 'section': 'how_it_works', 'key': 'step1_title',
     'label': 'Step 1 Title',
     'value': 'Search & Locate', 'content_type': 'text'},
    {'page': 'home', 'section': 'how_it_works', 'key': 'step1_desc',
     'label': 'Step 1 Description',
     'value': 'Enter your ZIP code or vehicle details. Our system instantly finds verified junkyards near you with the parts you need.',
     'content_type': 'text'},
    {'page': 'home', 'section': 'how_it_works', 'key': 'step2_title',
     'label': 'Step 2 Title',
     'value': 'Get Free Quotes', 'content_type': 'text'},
    {'page': 'home', 'section': 'how_it_works', 'key': 'step2_desc',
     'label': 'Step 2 Description',
     'value': 'Submit a single request to multiple vendors simultaneously. Compare prices, availability, and shipping options in real time.',
     'content_type': 'text'},
    {'page': 'home', 'section': 'how_it_works', 'key': 'step3_title',
     'label': 'Step 3 Title',
     'value': 'Order & Save', 'content_type': 'text'},
    {'page': 'home', 'section': 'how_it_works', 'key': 'step3_desc',
     'label': 'Step 3 Description',
     'value': 'Choose the best deal, order your parts, and save up to 80% compared to dealer prices. Fast shipping nationwide.',
     'content_type': 'text'},

    # CTA Banner Section (Home)
    {'page': 'home', 'section': 'cta_banner', 'key': 'heading',
     'label': 'Banner Heading (HTML allowed)',
     'value': 'Ready to Find Your <span style="background: linear-gradient(135deg, #93c5fd, #bfdbfe); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text;">Perfect Part?</span>',
     'content_type': 'html'},
    {'page': 'home', 'section': 'cta_banner', 'key': 'subheading',
     'label': 'Banner Subheading',
     'value': 'Join thousands of mechanics and car owners who save hundreds by using JYNM to source quality used auto parts across all 50 states.',
     'content_type': 'text'},
    {'page': 'home', 'section': 'cta_banner', 'key': 'button_text',
     'label': 'CTA Button Text',
     'value': 'Get Free Quote Now', 'content_type': 'text'},

    # ══════════════════════════════════════════════════════════════════
    # ABOUT PAGE
    # ══════════════════════════════════════════════════════════════════

    {'page': 'about', 'section': 'meta', 'key': 'title',
     'label': 'SEO Page Title',
     'value': 'About Us - Junkyards Near Me | The Future of Auto Salvage',
     'content_type': 'text'},
    {'page': 'about', 'section': 'meta', 'key': 'description',
     'label': 'SEO Meta Description',
     'value': 'Learn about Junkyards Near Me - connecting mechanics, enthusiasts, and car owners with over 1,000 verified junkyards across all 50 states. Save up to 70% on quality used auto parts.',
     'content_type': 'text'},

    {'page': 'about', 'section': 'hero', 'key': 'heading',
     'label': 'Hero Heading Line 1',
     'value': 'The Future of', 'content_type': 'text'},
    {'page': 'about', 'section': 'hero', 'key': 'heading_accent',
     'label': 'Hero Heading Line 2 (accent color)',
     'value': 'Auto Salvage', 'content_type': 'text'},
    {'page': 'about', 'section': 'hero', 'key': 'subheading',
     'label': 'Hero Subheading',
     'value': "We're revolutionizing how you find used auto parts. Connecting mechanics, enthusiasts, and car owners with the nation's most extensive inventory.",
     'content_type': 'text'},

    {'page': 'about', 'section': 'stats', 'key': 'label_1',
     'label': 'Stat 1 Label',
     'value': 'Active Junkyards', 'content_type': 'text'},
    {'page': 'about', 'section': 'stats', 'key': 'label_2',
     'label': 'Stat 2 Label',
     'value': 'States Covered', 'content_type': 'text'},
    {'page': 'about', 'section': 'stats', 'key': 'label_3',
     'label': 'Stat 3 Label',
     'value': 'Daily Searches', 'content_type': 'text'},
    {'page': 'about', 'section': 'stats', 'key': 'value_3',
     'label': 'Stat 3 Value',
     'value': '50k+', 'content_type': 'text'},
    {'page': 'about', 'section': 'stats', 'key': 'label_4',
     'label': 'Stat 4 Label',
     'value': 'Parts Found', 'content_type': 'text'},
    {'page': 'about', 'section': 'stats', 'key': 'value_4',
     'label': 'Stat 4 Value',
     'value': '1M+', 'content_type': 'text'},

    {'page': 'about', 'section': 'mission', 'key': 'title',
     'label': 'Mission Title',
     'value': 'Our Mission is', 'content_type': 'text'},
    {'page': 'about', 'section': 'mission', 'key': 'title_accent',
     'label': 'Mission Title Accent Word (blue)',
     'value': 'Simple', 'content_type': 'text'},
    {'page': 'about', 'section': 'mission', 'key': 'para_1',
     'label': 'Mission Paragraph 1',
     'value': "Finding quality used auto parts shouldn't be a hassle. We built Junkyards Near Me to bridge the gap between organized inventory and the people who need it most.",
     'content_type': 'text'},
    {'page': 'about', 'section': 'mission', 'key': 'para_2',
     'label': 'Mission Paragraph 2',
     'value': "Whether you're restoring a classic, fixing a daily driver, or running a repair shop, our platform gives you instant access to millions of parts across the country.",
     'content_type': 'text'},

    # ══════════════════════════════════════════════════════════════════
    # CONTACT PAGE
    # ══════════════════════════════════════════════════════════════════

    {'page': 'contact', 'section': 'meta', 'key': 'title',
     'label': 'SEO Page Title',
     'value': 'Contact Us - Get Help Finding Auto Parts',
     'content_type': 'text'},
    {'page': 'contact', 'section': 'meta', 'key': 'description',
     'label': 'SEO Meta Description',
     'value': "Contact Junkyards Near Me for support. Questions about finding parts, vendor inquiries, or technical support. We're here to help connect you with the right salvage yard.",
     'content_type': 'text'},

    {'page': 'contact', 'section': 'hero', 'key': 'heading',
     'label': 'Hero Heading',
     'value': "We'd Love to", 'content_type': 'text'},
    {'page': 'contact', 'section': 'hero', 'key': 'heading_accent',
     'label': 'Hero Heading Accent (blue)',
     'value': 'Hear from You', 'content_type': 'text'},
    {'page': 'contact', 'section': 'hero', 'key': 'subheading',
     'label': 'Hero Subheading',
     'value': 'Have questions about finding a part? Need help using our platform? Our team is here to assist you 24/7.',
     'content_type': 'text'},

    {'page': 'contact', 'section': 'info', 'key': 'address',
     'label': 'Office Address',
     'value': '123 Auto Salvage Way, Phoenix, AZ 85001, United States',
     'content_type': 'text'},
    {'page': 'contact', 'section': 'info', 'key': 'email',
     'label': 'Support Email',
     'value': 'support@jynm.com', 'content_type': 'text'},
    {'page': 'contact', 'section': 'info', 'key': 'phone',
     'label': 'Support Phone Number',
     'value': '+1 (800) 555-1234', 'content_type': 'text'},

    # ══════════════════════════════════════════════════════════════════
    # BROWSE STATES PAGE
    # ══════════════════════════════════════════════════════════════════

    {'page': 'browse', 'section': 'hero', 'key': 'heading',
     'label': 'Hero Heading (HTML allowed)',
     'value': 'Browse by <span class="block mt-2" style="color: #60a5fa">Location</span>',
     'content_type': 'html'},
    {'page': 'browse', 'section': 'hero', 'key': 'subheading',
     'label': 'Hero Subheading (HTML allowed)',
     'value': 'Find <strong style="color: #ffffff">quality auto parts</strong> from trusted salvage yards. Select your state to discover local junkyards.',
     'content_type': 'html'},

    # ══════════════════════════════════════════════════════════════════
    # ALL VENDORS / LISTINGS PAGE
    # ══════════════════════════════════════════════════════════════════

    {'page': 'vendors', 'section': 'hero', 'key': 'heading',
     'label': 'Hero Heading (HTML allowed)',
     'value': 'Browse All <span class="block md:inline mt-2 md:mt-0" style="color: #60a5fa">Junkyards</span>',
     'content_type': 'html'},
    {'page': 'vendors', 'section': 'hero', 'key': 'subheading',
     'label': 'Hero Subheading (HTML allowed)',
     'value': 'Find <strong style="color: #ffffff">quality auto parts</strong> from trusted salvage yards statewide. Filter by location and connect instantly.',
     'content_type': 'html'},

    # ══════════════════════════════════════════════════════════════════
    # BLOG PAGE
    # ══════════════════════════════════════════════════════════════════

    {'page': 'blog', 'section': 'meta', 'key': 'title',
     'label': 'SEO Page Title',
     'value': 'Blog — Junkyard Near Me | Auto Parts Tips & Guides',
     'content_type': 'text'},
    {'page': 'blog', 'section': 'meta', 'key': 'description',
     'label': 'SEO Meta Description',
     'value': 'Expert guides on buying used auto parts, DIY repairs, salvage yard tips, and industry news. Save money on your next repair with JYNM.',
     'content_type': 'text'},
    {'page': 'blog', 'section': 'hero', 'key': 'heading',
     'label': 'Hero Heading Line 1',
     'value': 'The Junkyard', 'content_type': 'text'},
    {'page': 'blog', 'section': 'hero', 'key': 'heading_accent',
     'label': 'Hero Heading Line 2 (blue)',
     'value': 'Journal', 'content_type': 'text'},
    {'page': 'blog', 'section': 'hero', 'key': 'subheading',
     'label': 'Hero Subheading',
     'value': 'Expert guides on pulling parts, salvaging tips, and the latest news from the used auto parts industry.',
     'content_type': 'text'},

    # ══════════════════════════════════════════════════════════════════
    # FAQ PAGE
    # ══════════════════════════════════════════════════════════════════

    {'page': 'faq', 'section': 'hero', 'key': 'heading',
     'label': 'Hero Heading (HTML allowed)',
     'value': 'Frequently Asked <span class="text-blue-400">Questions</span>',
     'content_type': 'html'},
    {'page': 'faq', 'section': 'hero', 'key': 'subheading',
     'label': 'Hero Subheading',
     'value': 'Everything you need to know about finding and buying used auto parts through our platform.',
     'content_type': 'text'},

    # ══════════════════════════════════════════════════════════════════
    # HOW IT WORKS PAGE
    # ══════════════════════════════════════════════════════════════════

    {'page': 'how_it_works', 'section': 'hero', 'key': 'heading',
     'label': 'Page Heading (HTML allowed)',
     'value': 'How It <span style="color:#2563eb">Works</span>',
     'content_type': 'html'},
    {'page': 'how_it_works', 'section': 'hero', 'key': 'subheading',
     'label': 'Page Subheading',
     'value': 'Find quality used auto parts in 4 simple steps. No hassle, no spam, just results.',
     'content_type': 'text'},
    {'page': 'how_it_works', 'section': 'steps', 'key': 'step1_title',
     'label': 'Step 1 Title',
     'value': 'Tell Us What You Need', 'content_type': 'text'},
    {'page': 'how_it_works', 'section': 'steps', 'key': 'step1_desc',
     'label': 'Step 1 Description',
     'value': "Fill out our simple form with your vehicle details (make, model, year) and the specific part you're looking for. Add your contact information and location.",
     'content_type': 'text'},
    {'page': 'how_it_works', 'section': 'steps', 'key': 'step2_title',
     'label': 'Step 2 Title',
     'value': 'We Connect You', 'content_type': 'text'},
    {'page': 'how_it_works', 'section': 'steps', 'key': 'step2_desc',
     'label': 'Step 2 Description',
     'value': 'Your request is instantly sent to our network of verified junkyards and auto salvage yards in your area. No need to call around - we do the work for you.',
     'content_type': 'text'},
    {'page': 'how_it_works', 'section': 'steps', 'key': 'step3_title',
     'label': 'Step 3 Title',
     'value': 'Receive Quotes Directly', 'content_type': 'text'},
    {'page': 'how_it_works', 'section': 'steps', 'key': 'step3_desc',
     'label': 'Step 3 Description',
     'value': 'Junkyards with your part in stock will contact you directly with pricing, availability, and shipping options. Compare offers and choose the best deal.',
     'content_type': 'text'},
    {'page': 'how_it_works', 'section': 'steps', 'key': 'step4_title',
     'label': 'Step 4 Title',
     'value': 'Get Your Part', 'content_type': 'text'},
    {'page': 'how_it_works', 'section': 'steps', 'key': 'step4_desc',
     'label': 'Step 4 Description',
     'value': 'Purchase directly from the junkyard of your choice. Arrange pickup or shipping, and get your quality used part at a fraction of the cost of new.',
     'content_type': 'text'},

    # ══════════════════════════════════════════════════════════════════
    # NAVBAR (GLOBAL)
    # ══════════════════════════════════════════════════════════════════

    {'page': 'navbar', 'section': 'brand', 'key': 'tagline',
     'label': 'Brand Tagline (below logo)',
     'value': 'AutoParts Hub', 'content_type': 'text'},
    {'page': 'navbar', 'section': 'cta', 'key': 'support_label',
     'label': 'Support Link Label',
     'value': 'Support', 'content_type': 'text'},

    # ══════════════════════════════════════════════════════════════════
    # FOOTER (GLOBAL)
    # ══════════════════════════════════════════════════════════════════

    {'page': 'footer', 'section': 'brand', 'key': 'description',
     'label': 'Footer Brand Description',
     'value': "The nation's most trusted marketplace for verified used auto parts. Connecting mechanics and enthusiasts with salvage yards nationwide.",
     'content_type': 'text'},

    {'page': 'footer', 'section': 'contact', 'key': 'phone',
     'label': 'Footer Phone Number',
     'value': '1-866-293-3731', 'content_type': 'text'},
    {'page': 'footer', 'section': 'contact', 'key': 'email',
     'label': 'Footer Email Address',
     'value': 'info@jynm.com', 'content_type': 'text'},

    {'page': 'footer', 'section': 'social', 'key': 'facebook',
     'label': 'Facebook URL',
     'value': 'https://www.facebook.com/JunkYardsNearMe', 'content_type': 'url'},
    {'page': 'footer', 'section': 'social', 'key': 'twitter',
     'label': 'Twitter / X URL',
     'value': 'https://x.com/junkyardsnearme', 'content_type': 'url'},
    {'page': 'footer', 'section': 'social', 'key': 'pinterest',
     'label': 'Pinterest URL',
     'value': 'https://www.pinterest.com/junkyardsnearme/', 'content_type': 'url'},
]
