"""
Default CMS content — every editable field across the entire website.
Safe to re-run (uses get_or_create). 200+ entries covering all pages.
"""

DEFAULT_CMS_CONTENT = [

    # ══════════════════════════════════════════════════════════════════
    # HOME PAGE
    # ══════════════════════════════════════════════════════════════════

    # Hero Section
    {'page': 'home', 'section': 'hero', 'key': 'heading',
     'label': 'Main Headline (use \\n for line breaks)',
     'value': 'FIND THE JUNKYARD\\nAUTO PARTS YOU NEED —\\nSEARCH IN SECONDS.',
     'content_type': 'text'},
    {'page': 'home', 'section': 'hero', 'key': 'subheading',
     'label': 'Sub-Headline (HTML allowed)',
     'value': 'Locate quality used auto parts from <span style="color: #fb923c; font-weight: 800">verified junkyards</span> near you!',
     'content_type': 'html'},
    {'page': 'home', 'section': 'hero', 'key': 'search_label',
     'label': 'Search Box Label Text',
     'value': 'Search by ZIP Code · Find junkyards near you instantly',
     'content_type': 'text'},
    {'page': 'home', 'section': 'hero', 'key': 'vehicle_search_label',
     'label': 'Vehicle Search Label',
     'value': 'Or search by vehicle details',
     'content_type': 'text'},
    {'page': 'home', 'section': 'hero', 'key': 'cta_primary_text',
     'label': 'Primary Button Text',
     'value': 'Browse All Vendors', 'content_type': 'text'},
    {'page': 'home', 'section': 'hero', 'key': 'cta_primary_link',
     'label': 'Primary Button Link',
     'value': '/vendors', 'content_type': 'url'},
    {'page': 'home', 'section': 'hero', 'key': 'cta_secondary_text',
     'label': 'Secondary Button Text',
     'value': 'How It Works', 'content_type': 'text'},
    {'page': 'home', 'section': 'hero', 'key': 'cta_secondary_link',
     'label': 'Secondary Button Link',
     'value': '/how-it-works', 'content_type': 'url'},
    {'page': 'home', 'section': 'hero', 'key': 'trust_badge_1',
     'label': 'Trust Badge 1',
     'value': 'No Spam Guarantee', 'content_type': 'text'},
    {'page': 'home', 'section': 'hero', 'key': 'trust_badge_2',
     'label': 'Trust Badge 2',
     'value': 'Instant Quotes', 'content_type': 'text'},
    {'page': 'home', 'section': 'hero', 'key': 'bg_image',
     'label': 'Hero Background Image',
     'value': '/heroes/junkyard-night.jpg', 'content_type': 'image'},

    # Stats Strip
    {'page': 'home', 'section': 'stats', 'key': 'stat1_label',
     'label': 'Stat 1 Label',
     'value': 'Verified Junkyards', 'content_type': 'text'},
    {'page': 'home', 'section': 'stats', 'key': 'stat2_label',
     'label': 'Stat 2 Label',
     'value': 'Parts Listed', 'content_type': 'text'},
    {'page': 'home', 'section': 'stats', 'key': 'stat3_label',
     'label': 'Stat 3 Label',
     'value': 'Coverage', 'content_type': 'text'},
    {'page': 'home', 'section': 'stats', 'key': 'stat4_label',
     'label': 'Stat 4 Label',
     'value': 'Savings vs. Dealer', 'content_type': 'text'},

    # Trust Pillars Section
    {'page': 'home', 'section': 'trust_pillars', 'key': 'badge_label',
     'label': 'Section Badge Text',
     'value': 'Why Trust JYNM', 'content_type': 'text'},
    {'page': 'home', 'section': 'trust_pillars', 'key': 'heading',
     'label': 'Section Heading (HTML allowed)',
     'value': 'Built on <span class="text-blue-600">Reliability</span> &amp; Transparency',
     'content_type': 'html'},
    {'page': 'home', 'section': 'trust_pillars', 'key': 'card1_icon',
     'label': 'Card 1 Icon (emoji)',
     'value': '🔒', 'content_type': 'text'},
    {'page': 'home', 'section': 'trust_pillars', 'key': 'card1_title',
     'label': 'Card 1 Title',
     'value': 'Verified Network', 'content_type': 'text'},
    {'page': 'home', 'section': 'trust_pillars', 'key': 'card1_desc',
     'label': 'Card 1 Description',
     'value': 'Every junkyard is manually vetted. We only list licensed, legitimate salvage yards you can trust.',
     'content_type': 'text'},
    {'page': 'home', 'section': 'trust_pillars', 'key': 'card2_icon',
     'label': 'Card 2 Icon (emoji)',
     'value': '⚡', 'content_type': 'text'},
    {'page': 'home', 'section': 'trust_pillars', 'key': 'card2_title',
     'label': 'Card 2 Title',
     'value': 'Instant Quotes', 'content_type': 'text'},
    {'page': 'home', 'section': 'trust_pillars', 'key': 'card2_desc',
     'label': 'Card 2 Description',
     'value': 'One request reaches multiple vendors simultaneously. Get competitive quotes without the phone tag.',
     'content_type': 'text'},
    {'page': 'home', 'section': 'trust_pillars', 'key': 'card3_icon',
     'label': 'Card 3 Icon (emoji)',
     'value': '🛡', 'content_type': 'text'},
    {'page': 'home', 'section': 'trust_pillars', 'key': 'card3_title',
     'label': 'Card 3 Title',
     'value': 'Zero Spam Promise', 'content_type': 'text'},
    {'page': 'home', 'section': 'trust_pillars', 'key': 'card3_desc',
     'label': 'Card 3 Description',
     'value': 'We never sell your data. Your contact info goes directly and only to the junkyard you choose.',
     'content_type': 'text'},
    {'page': 'home', 'section': 'trust_pillars', 'key': 'card4_icon',
     'label': 'Card 4 Icon (emoji)',
     'value': '💰', 'content_type': 'text'},
    {'page': 'home', 'section': 'trust_pillars', 'key': 'card4_title',
     'label': 'Card 4 Title',
     'value': 'Best Prices Guaranteed', 'content_type': 'text'},
    {'page': 'home', 'section': 'trust_pillars', 'key': 'card4_desc',
     'label': 'Card 4 Description',
     'value': 'Compare hundreds of vendors in seconds. Save up to 80% vs. dealer pricing with real-time availability.',
     'content_type': 'text'},

    # How It Works Section (Home)
    {'page': 'home', 'section': 'how_it_works', 'key': 'badge_label',
     'label': 'Section Badge Text',
     'value': 'Simple Process', 'content_type': 'text'},
    {'page': 'home', 'section': 'how_it_works', 'key': 'heading',
     'label': 'Section Heading (HTML allowed)',
     'value': 'How It <span style="color: #2563eb">Works</span>', 'content_type': 'html'},
    {'page': 'home', 'section': 'how_it_works', 'key': 'subheading',
     'label': 'Section Subheading',
     'value': 'Three simple steps to find the exact used auto parts you need at the best price.',
     'content_type': 'text'},
    {'page': 'home', 'section': 'how_it_works', 'key': 'step1_title',
     'label': 'Step 1 Title',
     'value': 'Search &amp; Locate', 'content_type': 'text'},
    {'page': 'home', 'section': 'how_it_works', 'key': 'step1_desc',
     'label': 'Step 1 Description',
     'value': 'Enter your ZIP code or vehicle details. Our system instantly finds verified junkyards near you with the parts you need.',
     'content_type': 'text'},
    {'page': 'home', 'section': 'how_it_works', 'key': 'step2_title',
     'label': 'Step 2 Title',
     'value': 'Get Free Quotes', 'content_type': 'text'},
    {'page': 'home', 'section': 'how_it_works', 'key': 'step2_desc',
     'label': 'Step 2 Description',
     'value': 'Submit a single request to multiple vendors simultaneously. Compare prices, availability, and shipping options in real time.',
     'content_type': 'text'},
    {'page': 'home', 'section': 'how_it_works', 'key': 'step3_title',
     'label': 'Step 3 Title',
     'value': 'Order &amp; Save', 'content_type': 'text'},
    {'page': 'home', 'section': 'how_it_works', 'key': 'step3_desc',
     'label': 'Step 3 Description',
     'value': 'Choose the best deal, order your parts, and save up to 80% compared to dealer prices. Fast shipping nationwide.',
     'content_type': 'text'},
    {'page': 'home', 'section': 'how_it_works', 'key': 'cta_text',
     'label': 'How It Works CTA Button',
     'value': 'See Full Guide', 'content_type': 'text'},
    {'page': 'home', 'section': 'how_it_works', 'key': 'cta_link',
     'label': 'How It Works CTA Link',
     'value': '/how-it-works', 'content_type': 'url'},

    # CTA Banner Section (Home)
    {'page': 'home', 'section': 'cta_banner', 'key': 'heading',
     'label': 'Banner Heading (HTML allowed)',
     'value': 'Ready to Find Your <span style="background: linear-gradient(135deg, #93c5fd, #bfdbfe); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text;">Perfect Part?</span>',
     'content_type': 'html'},
    {'page': 'home', 'section': 'cta_banner', 'key': 'subheading',
     'label': 'Banner Subheading',
     'value': 'Join thousands of mechanics and car owners who save hundreds by using JYNM to source quality used auto parts across all 50 states.',
     'content_type': 'text'},
    {'page': 'home', 'section': 'cta_banner', 'key': 'button_text',
     'label': 'CTA Button Text',
     'value': 'Get Free Quote Now', 'content_type': 'text'},
    {'page': 'home', 'section': 'cta_banner', 'key': 'button_link',
     'label': 'CTA Button Link',
     'value': '/quote', 'content_type': 'url'},
    {'page': 'home', 'section': 'cta_banner', 'key': 'badge_text',
     'label': 'Banner Badge Text',
     'value': '100% Free · No Obligations', 'content_type': 'text'},

    # Business CTA Section (Home)
    {'page': 'home', 'section': 'business_cta', 'key': 'heading',
     'label': 'Business CTA Heading (HTML allowed)',
     'value': 'Transform Your <span style="color:#f97316">Business</span>',
     'content_type': 'html'},
    {'page': 'home', 'section': 'business_cta', 'key': 'subheading',
     'label': 'Business CTA Subheading',
     'value': "Are you a junkyard owner or salvage yard operator? List your inventory and connect with thousands of buyers actively searching for parts.",
     'content_type': 'text'},
    {'page': 'home', 'section': 'business_cta', 'key': 'button_text',
     'label': 'Business CTA Button Text',
     'value': 'List Your Yard Free', 'content_type': 'text'},
    {'page': 'home', 'section': 'business_cta', 'key': 'button_link',
     'label': 'Business CTA Button Link',
     'value': '/add-your-yard', 'content_type': 'url'},
    {'page': 'home', 'section': 'business_cta', 'key': 'feature1',
     'label': 'Business Feature 1',
     'value': 'Reach 50k+ monthly buyers', 'content_type': 'text'},
    {'page': 'home', 'section': 'business_cta', 'key': 'feature2',
     'label': 'Business Feature 2',
     'value': 'Free basic listing', 'content_type': 'text'},
    {'page': 'home', 'section': 'business_cta', 'key': 'feature3',
     'label': 'Business Feature 3',
     'value': 'Premium placement available', 'content_type': 'text'},

    # ══════════════════════════════════════════════════════════════════
    # ABOUT PAGE
    # ══════════════════════════════════════════════════════════════════

    {'page': 'about', 'section': 'meta', 'key': 'title',
     'label': 'SEO Page Title',
     'value': 'About Us - Junkyards Near Me | The Future of Auto Salvage',
     'content_type': 'text'},
    {'page': 'about', 'section': 'meta', 'key': 'description',
     'label': 'SEO Meta Description',
     'value': 'Learn about Junkyards Near Me - connecting mechanics, enthusiasts, and car owners with over 1,000 verified junkyards across all 50 states. Save up to 70% on quality used auto parts.',
     'content_type': 'text'},

    {'page': 'about', 'section': 'hero', 'key': 'bg_image',
     'label': 'Hero Background Image',
     'value': '/heroes/aerial-night.png', 'content_type': 'image'},
    {'page': 'about', 'section': 'hero', 'key': 'badge_text',
     'label': 'Hero Badge Text',
     'value': 'About JYNM', 'content_type': 'text'},
    {'page': 'about', 'section': 'hero', 'key': 'heading',
     'label': 'Hero Heading Line 1',
     'value': 'The Future of', 'content_type': 'text'},
    {'page': 'about', 'section': 'hero', 'key': 'heading_accent',
     'label': 'Hero Heading Line 2 (accent color)',
     'value': 'Auto Salvage', 'content_type': 'text'},
    {'page': 'about', 'section': 'hero', 'key': 'subheading',
     'label': 'Hero Subheading',
     'value': "We're revolutionizing how you find used auto parts. Connecting mechanics, enthusiasts, and car owners with the nation's most extensive inventory.",
     'content_type': 'text'},

    {'page': 'about', 'section': 'stats', 'key': 'label_1',
     'label': 'Stat 1 Label',
     'value': 'Active Junkyards', 'content_type': 'text'},
    {'page': 'about', 'section': 'stats', 'key': 'label_2',
     'label': 'Stat 2 Label',
     'value': 'States Covered', 'content_type': 'text'},
    {'page': 'about', 'section': 'stats', 'key': 'label_3',
     'label': 'Stat 3 Label',
     'value': 'Daily Searches', 'content_type': 'text'},
    {'page': 'about', 'section': 'stats', 'key': 'value_3',
     'label': 'Stat 3 Value',
     'value': '50k+', 'content_type': 'text'},
    {'page': 'about', 'section': 'stats', 'key': 'label_4',
     'label': 'Stat 4 Label',
     'value': 'Parts Found', 'content_type': 'text'},
    {'page': 'about', 'section': 'stats', 'key': 'value_4',
     'label': 'Stat 4 Value',
     'value': '1M+', 'content_type': 'text'},

    {'page': 'about', 'section': 'mission', 'key': 'title',
     'label': 'Mission Title',
     'value': 'Our Mission is', 'content_type': 'text'},
    {'page': 'about', 'section': 'mission', 'key': 'title_accent',
     'label': 'Mission Title Accent Word (blue)',
     'value': 'Simple', 'content_type': 'text'},
    {'page': 'about', 'section': 'mission', 'key': 'para_1',
     'label': 'Mission Paragraph 1',
     'value': "Finding quality used auto parts shouldn't be a hassle. We built Junkyards Near Me to bridge the gap between organized inventory and the people who need it most.",
     'content_type': 'textarea'},
    {'page': 'about', 'section': 'mission', 'key': 'para_2',
     'label': 'Mission Paragraph 2',
     'value': "Whether you're restoring a classic, fixing a daily driver, or running a repair shop, our platform gives you instant access to millions of parts across the country.",
     'content_type': 'textarea'},
    {'page': 'about', 'section': 'mission', 'key': 'image',
     'label': 'Mission Section Image',
     'value': '/images/about-mission.jpg', 'content_type': 'image'},

    # About Features
    {'page': 'about', 'section': 'features', 'key': 'badge_label',
     'label': 'Features Section Badge',
     'value': 'What We Offer', 'content_type': 'text'},
    {'page': 'about', 'section': 'features', 'key': 'heading',
     'label': 'Features Section Heading (HTML)',
     'value': 'Why Choose <span class="text-blue-600">Used?</span>',
     'content_type': 'html'},
    {'page': 'about', 'section': 'features', 'key': 'feature1_title',
     'label': 'Feature 1 Title',
     'value': 'Nationwide Network', 'content_type': 'text'},
    {'page': 'about', 'section': 'features', 'key': 'feature1_desc',
     'label': 'Feature 1 Description',
     'value': 'Determine availability across our massive network of over 1,000 verified junkyards in all 50 states.',
     'content_type': 'textarea'},
    {'page': 'about', 'section': 'features', 'key': 'feature2_title',
     'label': 'Feature 2 Title',
     'value': 'Smart Search', 'content_type': 'text'},
    {'page': 'about', 'section': 'features', 'key': 'feature2_desc',
     'label': 'Feature 2 Description',
     'value': 'Instantly filter by vehicle make, model, year, and part type to find exactly what you need in seconds.',
     'content_type': 'textarea'},
    {'page': 'about', 'section': 'features', 'key': 'feature3_title',
     'label': 'Feature 3 Title',
     'value': 'Direct Contact', 'content_type': 'text'},
    {'page': 'about', 'section': 'features', 'key': 'feature3_desc',
     'label': 'Feature 3 Description',
     'value': 'Get direct access to junkyard phone numbers, addresses, and websites. No middlemen, no hidden fees.',
     'content_type': 'textarea'},

    # About CTA
    {'page': 'about', 'section': 'cta', 'key': 'heading',
     'label': 'About CTA Heading',
     'value': "Ready to Find Your Part?", 'content_type': 'text'},
    {'page': 'about', 'section': 'cta', 'key': 'button_text',
     'label': 'About CTA Button Text',
     'value': 'Browse Junkyards', 'content_type': 'text'},
    {'page': 'about', 'section': 'cta', 'key': 'button_link',
     'label': 'About CTA Button Link',
     'value': '/vendors', 'content_type': 'url'},

    # ══════════════════════════════════════════════════════════════════
    # CONTACT PAGE
    # ══════════════════════════════════════════════════════════════════

    {'page': 'contact', 'section': 'meta', 'key': 'title',
     'label': 'SEO Page Title',
     'value': 'Contact Us - Get Help Finding Auto Parts',
     'content_type': 'text'},
    {'page': 'contact', 'section': 'meta', 'key': 'description',
     'label': 'SEO Meta Description',
     'value': "Contact Junkyards Near Me for support. Questions about finding parts, vendor inquiries, or technical support. We're here to help connect you with the right salvage yard.",
     'content_type': 'text'},

    {'page': 'contact', 'section': 'hero', 'key': 'bg_image',
     'label': 'Hero Background Image',
     'value': '/heroes/contact-bg.jpg', 'content_type': 'image'},
    {'page': 'contact', 'section': 'hero', 'key': 'heading',
     'label': 'Hero Heading',
     'value': "We'd Love to", 'content_type': 'text'},
    {'page': 'contact', 'section': 'hero', 'key': 'heading_accent',
     'label': 'Hero Heading Accent (blue)',
     'value': 'Hear from You', 'content_type': 'text'},
    {'page': 'contact', 'section': 'hero', 'key': 'subheading',
     'label': 'Hero Subheading',
     'value': 'Have questions about finding a part? Need help using our platform? Our team is here to assist you 24/7.',
     'content_type': 'text'},

    {'page': 'contact', 'section': 'info', 'key': 'address',
     'label': 'Office Address',
     'value': '123 Auto Salvage Way, Phoenix, AZ 85001, United States',
     'content_type': 'text'},
    {'page': 'contact', 'section': 'info', 'key': 'email',
     'label': 'Support Email',
     'value': 'support@jynm.com', 'content_type': 'text'},
    {'page': 'contact', 'section': 'info', 'key': 'phone',
     'label': 'Support Phone Number',
     'value': '+1 (800) 555-1234', 'content_type': 'text'},
    {'page': 'contact', 'section': 'info', 'key': 'hours',
     'label': 'Business Hours',
     'value': 'Mon–Fri: 8AM – 6PM EST', 'content_type': 'text'},
    {'page': 'contact', 'section': 'info', 'key': 'address_label',
     'label': 'Address Card Title',
     'value': 'Our Office', 'content_type': 'text'},
    {'page': 'contact', 'section': 'info', 'key': 'email_label',
     'label': 'Email Card Title',
     'value': 'Email Us', 'content_type': 'text'},
    {'page': 'contact', 'section': 'info', 'key': 'phone_label',
     'label': 'Phone Card Title',
     'value': 'Call Us', 'content_type': 'text'},
    {'page': 'contact', 'section': 'info', 'key': 'hours_label',
     'label': 'Hours Card Title',
     'value': 'Business Hours', 'content_type': 'text'},

    # Contact Form
    {'page': 'contact', 'section': 'form', 'key': 'heading',
     'label': 'Form Section Heading',
     'value': 'Send Us a Message', 'content_type': 'text'},
    {'page': 'contact', 'section': 'form', 'key': 'name_label',
     'label': 'Name Field Label',
     'value': 'Full Name', 'content_type': 'text'},
    {'page': 'contact', 'section': 'form', 'key': 'email_label',
     'label': 'Email Field Label',
     'value': 'Email Address', 'content_type': 'text'},
    {'page': 'contact', 'section': 'form', 'key': 'subject_label',
     'label': 'Subject Field Label',
     'value': 'Subject', 'content_type': 'text'},
    {'page': 'contact', 'section': 'form', 'key': 'message_label',
     'label': 'Message Field Label',
     'value': 'Your Message', 'content_type': 'text'},
    {'page': 'contact', 'section': 'form', 'key': 'submit_text',
     'label': 'Submit Button Text',
     'value': 'Send Message', 'content_type': 'text'},
    {'page': 'contact', 'section': 'form', 'key': 'success_message',
     'label': 'Form Success Message',
     'value': "Thank you! We'll get back to you within 24 hours.", 'content_type': 'text'},

    # ══════════════════════════════════════════════════════════════════
    # BROWSE STATES PAGE
    # ══════════════════════════════════════════════════════════════════

    {'page': 'browse', 'section': 'hero', 'key': 'bg_image',
     'label': 'Hero Background Image',
     'value': '/heroes/stacked-cars.png', 'content_type': 'image'},
    {'page': 'browse', 'section': 'hero', 'key': 'heading',
     'label': 'Hero Heading (HTML allowed)',
     'value': 'Browse by <span class="block mt-2" style="color: #60a5fa">Location</span>',
     'content_type': 'html'},
    {'page': 'browse', 'section': 'hero', 'key': 'subheading',
     'label': 'Hero Subheading (HTML allowed)',
     'value': 'Find <strong style="color: #ffffff">quality auto parts</strong> from trusted salvage yards. Select your state to discover local junkyards.',
     'content_type': 'html'},
    {'page': 'browse', 'section': 'hero', 'key': 'stats_text',
     'label': 'Hero Stats Label (above map)',
     'value': 'States • Vendors', 'content_type': 'text'},

    {'page': 'browse', 'section': 'map', 'key': 'heading',
     'label': 'Map Section Heading',
     'value': 'Click a State to Browse', 'content_type': 'text'},
    {'page': 'browse', 'section': 'map', 'key': 'search_placeholder',
     'label': 'State Search Placeholder',
     'value': 'Search for a state...', 'content_type': 'text'},
    {'page': 'browse', 'section': 'map', 'key': 'results_heading',
     'label': 'Results Section Heading',
     'value': 'All States', 'content_type': 'text'},
    {'page': 'browse', 'section': 'map', 'key': 'empty_state_text',
     'label': 'No Results Text',
     'value': 'No states found', 'content_type': 'text'},
    {'page': 'browse', 'section': 'map', 'key': 'empty_state_sub',
     'label': 'No Results Subtext',
     'value': 'Try adjusting your search', 'content_type': 'text'},
    {'page': 'browse', 'section': 'map', 'key': 'clear_search_btn',
     'label': 'Clear Search Button',
     'value': 'Clear Search', 'content_type': 'text'},

    # ══════════════════════════════════════════════════════════════════
    # ALL VENDORS / LISTINGS PAGE
    # ══════════════════════════════════════════════════════════════════

    {'page': 'vendors', 'section': 'meta', 'key': 'title',
     'label': 'SEO Page Title',
     'value': 'All Junkyards - Browse Auto Salvage Yards Nationwide',
     'content_type': 'text'},
    {'page': 'vendors', 'section': 'meta', 'key': 'description',
     'label': 'SEO Meta Description',
     'value': 'Browse our complete directory of verified auto salvage yards. Find used auto parts, compare prices, and connect with local junkyards.',
     'content_type': 'text'},

    {'page': 'vendors', 'section': 'hero', 'key': 'bg_image',
     'label': 'Hero Background Image',
     'value': '/heroes/salvage-sunset.png', 'content_type': 'image'},
    {'page': 'vendors', 'section': 'hero', 'key': 'heading',
     'label': 'Hero Heading (HTML allowed)',
     'value': 'Browse All <span class="block md:inline mt-2 md:mt-0" style="color: #60a5fa">Junkyards</span>',
     'content_type': 'html'},
    {'page': 'vendors', 'section': 'hero', 'key': 'subheading',
     'label': 'Hero Subheading (HTML allowed)',
     'value': 'Find <strong style="color: #ffffff">quality auto parts</strong> from trusted salvage yards statewide. Filter by location and connect instantly.',
     'content_type': 'html'},

    {'page': 'vendors', 'section': 'filters', 'key': 'search_placeholder',
     'label': 'Search Bar Placeholder',
     'value': 'Search by name, city, state...', 'content_type': 'text'},
    {'page': 'vendors', 'section': 'filters', 'key': 'state_filter_label',
     'label': 'State Filter Label',
     'value': 'Filter by State', 'content_type': 'text'},
    {'page': 'vendors', 'section': 'filters', 'key': 'clear_btn',
     'label': 'Clear Filters Button',
     'value': 'Clear All', 'content_type': 'text'},
    {'page': 'vendors', 'section': 'filters', 'key': 'all_states_option',
     'label': 'All States Dropdown Option',
     'value': 'All States', 'content_type': 'text'},

    {'page': 'vendors', 'section': 'results', 'key': 'loading_text',
     'label': 'Loading Text',
     'value': 'Loading junkyards...', 'content_type': 'text'},
    {'page': 'vendors', 'section': 'results', 'key': 'no_results_heading',
     'label': 'No Results Heading',
     'value': 'No junkyards found', 'content_type': 'text'},
    {'page': 'vendors', 'section': 'results', 'key': 'no_results_sub',
     'label': 'No Results Subtext',
     'value': 'Try broadening your search or clearing filters.', 'content_type': 'text'},
    {'page': 'vendors', 'section': 'results', 'key': 'view_details_btn',
     'label': 'View Details Button Text',
     'value': 'View Details', 'content_type': 'text'},

    # ══════════════════════════════════════════════════════════════════
    # BLOG PAGE
    # ══════════════════════════════════════════════════════════════════

    {'page': 'blog', 'section': 'meta', 'key': 'title',
     'label': 'SEO Page Title',
     'value': 'Blog — Junkyard Near Me | Auto Parts Tips &amp; Guides',
     'content_type': 'text'},
    {'page': 'blog', 'section': 'meta', 'key': 'description',
     'label': 'SEO Meta Description',
     'value': 'Expert guides on buying used auto parts, DIY repairs, salvage yard tips, and industry news. Save money on your next repair with JYNM.',
     'content_type': 'text'},

    {'page': 'blog', 'section': 'hero', 'key': 'bg_image',
     'label': 'Hero Background Image',
     'value': '/heroes/blog-bg.jpg', 'content_type': 'image'},
    {'page': 'blog', 'section': 'hero', 'key': 'badge_text',
     'label': 'Hero Badge Text',
     'value': 'Expert Insights', 'content_type': 'text'},
    {'page': 'blog', 'section': 'hero', 'key': 'heading',
     'label': 'Hero Heading Line 1',
     'value': 'The Junkyard', 'content_type': 'text'},
    {'page': 'blog', 'section': 'hero', 'key': 'heading_accent',
     'label': 'Hero Heading Line 2 (blue)',
     'value': 'Journal', 'content_type': 'text'},
    {'page': 'blog', 'section': 'hero', 'key': 'subheading',
     'label': 'Hero Subheading',
     'value': 'Expert guides on pulling parts, salvaging tips, and the latest news from the used auto parts industry.',
     'content_type': 'text'},
    {'page': 'blog', 'section': 'hero', 'key': 'search_placeholder',
     'label': 'Blog Search Placeholder',
     'value': 'Search articles...', 'content_type': 'text'},
    {'page': 'blog', 'section': 'hero', 'key': 'articles_label',
     'label': 'Articles Section Label',
     'value': 'Latest Articles', 'content_type': 'text'},

    # ══════════════════════════════════════════════════════════════════
    # FAQ PAGE
    # ══════════════════════════════════════════════════════════════════

    {'page': 'faq', 'section': 'meta', 'key': 'title',
     'label': 'SEO Page Title',
     'value': 'FAQ - Junkyards Near Me | Frequently Asked Questions',
     'content_type': 'text'},
    {'page': 'faq', 'section': 'meta', 'key': 'description',
     'label': 'SEO Meta Description',
     'value': 'Answers to your most common questions about finding used auto parts, how our platform works, shipping, returns, and working with verified junkyards.',
     'content_type': 'text'},
    {'page': 'faq', 'section': 'hero', 'key': 'bg_image',
     'label': 'Hero Background Image',
     'value': '/heroes/faq-bg.jpg', 'content_type': 'image'},
    {'page': 'faq', 'section': 'hero', 'key': 'heading',
     'label': 'Hero Heading (HTML allowed)',
     'value': 'Frequently Asked <span class="text-blue-400">Questions</span>',
     'content_type': 'html'},
    {'page': 'faq', 'section': 'hero', 'key': 'subheading',
     'label': 'Hero Subheading',
     'value': 'Everything you need to know about finding and buying used auto parts through our platform.',
     'content_type': 'text'},
    {'page': 'faq', 'section': 'hero', 'key': 'search_placeholder',
     'label': 'FAQ Search Placeholder',
     'value': 'Search questions...', 'content_type': 'text'},
    {'page': 'faq', 'section': 'categories', 'key': 'general',
     'label': 'Category: General',
     'value': 'General', 'content_type': 'text'},
    {'page': 'faq', 'section': 'categories', 'key': 'buying',
     'label': 'Category: Buying Parts',
     'value': 'Buying Parts', 'content_type': 'text'},
    {'page': 'faq', 'section': 'categories', 'key': 'shipping',
     'label': 'Category: Shipping & Returns',
     'value': 'Shipping &amp; Returns', 'content_type': 'text'},
    {'page': 'faq', 'section': 'cta', 'key': 'heading',
     'label': 'FAQ CTA Heading',
     'value': 'Still Have Questions?', 'content_type': 'text'},
    {'page': 'faq', 'section': 'cta', 'key': 'subtext',
     'label': 'FAQ CTA Subtext',
     'value': "Our support team is ready to help you find exactly what you need.", 'content_type': 'text'},
    {'page': 'faq', 'section': 'cta', 'key': 'button_text',
     'label': 'FAQ CTA Button',
     'value': 'Contact Support', 'content_type': 'text'},
    {'page': 'faq', 'section': 'cta', 'key': 'button_link',
     'label': 'FAQ CTA Button Link',
     'value': '/contact', 'content_type': 'url'},

    # ══════════════════════════════════════════════════════════════════
    # HOW IT WORKS PAGE
    # ══════════════════════════════════════════════════════════════════

    {'page': 'how_it_works', 'section': 'meta', 'key': 'title',
     'label': 'SEO Page Title',
     'value': 'How It Works - Find Used Auto Parts | Junkyards Near Me',
     'content_type': 'text'},
    {'page': 'how_it_works', 'section': 'meta', 'key': 'description',
     'label': 'SEO Meta Description',
     'value': 'Learn how to find quality used auto parts in 4 simple steps. Submit a request and get quotes from verified junkyards nationwide.',
     'content_type': 'text'},
    {'page': 'how_it_works', 'section': 'hero', 'key': 'bg_image',
     'label': 'Hero Background Image',
     'value': '/heroes/how-it-works-bg.jpg', 'content_type': 'image'},
    {'page': 'how_it_works', 'section': 'hero', 'key': 'heading',
     'label': 'Page Heading (HTML allowed)',
     'value': 'How It <span style="color:#2563eb">Works</span>',
     'content_type': 'html'},
    {'page': 'how_it_works', 'section': 'hero', 'key': 'subheading',
     'label': 'Page Subheading',
     'value': 'Find quality used auto parts in 4 simple steps. No hassle, no spam, just results.',
     'content_type': 'text'},
    {'page': 'how_it_works', 'section': 'steps', 'key': 'step1_number',
     'label': 'Step 1 Number Display',
     'value': '01', 'content_type': 'text'},
    {'page': 'how_it_works', 'section': 'steps', 'key': 'step1_title',
     'label': 'Step 1 Title',
     'value': 'Tell Us What You Need', 'content_type': 'text'},
    {'page': 'how_it_works', 'section': 'steps', 'key': 'step1_desc',
     'label': 'Step 1 Description',
     'value': "Fill out our simple form with your vehicle details (make, model, year) and the specific part you're looking for. Add your contact information and location.",
     'content_type': 'textarea'},
    {'page': 'how_it_works', 'section': 'steps', 'key': 'step2_number',
     'label': 'Step 2 Number Display',
     'value': '02', 'content_type': 'text'},
    {'page': 'how_it_works', 'section': 'steps', 'key': 'step2_title',
     'label': 'Step 2 Title',
     'value': 'We Notify Our Network', 'content_type': 'text'},
    {'page': 'how_it_works', 'section': 'steps', 'key': 'step2_desc',
     'label': 'Step 2 Description',
     'value': 'Your request is instantly sent to our network of verified junkyards and auto salvage yards in your area. No need to call around - we do the work for you.',
     'content_type': 'textarea'},
    {'page': 'how_it_works', 'section': 'steps', 'key': 'step3_number',
     'label': 'Step 3 Number Display',
     'value': '03', 'content_type': 'text'},
    {'page': 'how_it_works', 'section': 'steps', 'key': 'step3_title',
     'label': 'Step 3 Title',
     'value': 'Receive Free Quotes', 'content_type': 'text'},
    {'page': 'how_it_works', 'section': 'steps', 'key': 'step3_desc',
     'label': 'Step 3 Description',
     'value': 'Junkyards with your part in stock will contact you directly with pricing, availability, and shipping options. Compare offers and choose the best deal.',
     'content_type': 'textarea'},
    {'page': 'how_it_works', 'section': 'steps', 'key': 'step4_number',
     'label': 'Step 4 Number Display',
     'value': '04', 'content_type': 'text'},
    {'page': 'how_it_works', 'section': 'steps', 'key': 'step4_title',
     'label': 'Step 4 Title',
     'value': 'Order &amp; Save', 'content_type': 'text'},
    {'page': 'how_it_works', 'section': 'steps', 'key': 'step4_desc',
     'label': 'Step 4 Description',
     'value': 'Purchase directly from the junkyard of your choice. Arrange pickup or shipping, and get your quality used part at a fraction of the cost of new.',
     'content_type': 'textarea'},

    # How It Works CTA
    {'page': 'how_it_works', 'section': 'cta', 'key': 'heading',
     'label': 'CTA Section Heading',
     'value': "Ready to Find Your Part?", 'content_type': 'text'},
    {'page': 'how_it_works', 'section': 'cta', 'key': 'subtext',
     'label': 'CTA Section Subtext',
     'value': "It's 100% free and takes less than 2 minutes to submit your request.", 'content_type': 'text'},
    {'page': 'how_it_works', 'section': 'cta', 'key': 'button_text',
     'label': 'CTA Button Text',
     'value': 'Submit a Free Request', 'content_type': 'text'},
    {'page': 'how_it_works', 'section': 'cta', 'key': 'button_link',
     'label': 'CTA Button Link',
     'value': '/quote', 'content_type': 'url'},

    # ══════════════════════════════════════════════════════════════════
    # NAVBAR (GLOBAL)
    # ══════════════════════════════════════════════════════════════════

    {'page': 'navbar', 'section': 'brand', 'key': 'tagline',
     'label': 'Brand Tagline (below logo)',
     'value': 'AutoParts Hub', 'content_type': 'text'},
    {'page': 'navbar', 'section': 'brand', 'key': 'logo',
     'label': 'Logo Image',
     'value': '/jynm_logo.png', 'content_type': 'image'},
    {'page': 'navbar', 'section': 'links', 'key': 'browse_label',
     'label': 'Browse Nav Link Label',
     'value': 'Browse', 'content_type': 'text'},
    {'page': 'navbar', 'section': 'links', 'key': 'vendors_label',
     'label': 'Vendors Nav Link Label',
     'value': 'Vendors', 'content_type': 'text'},
    {'page': 'navbar', 'section': 'links', 'key': 'blog_label',
     'label': 'Blog Nav Link Label',
     'value': 'Blog', 'content_type': 'text'},
    {'page': 'navbar', 'section': 'links', 'key': 'about_label',
     'label': 'About Nav Link Label',
     'value': 'About', 'content_type': 'text'},
    {'page': 'navbar', 'section': 'cta', 'key': 'support_label',
     'label': 'Support Link Label',
     'value': 'Support', 'content_type': 'text'},
    {'page': 'navbar', 'section': 'cta', 'key': 'add_yard_label',
     'label': 'Add Your Yard Button Text',
     'value': 'Add Your Yard', 'content_type': 'text'},
    {'page': 'navbar', 'section': 'cta', 'key': 'phone',
     'label': 'Navbar Phone Number',
     'value': '1-866-293-3731', 'content_type': 'text'},

    # ══════════════════════════════════════════════════════════════════
    # FOOTER (GLOBAL)
    # ══════════════════════════════════════════════════════════════════

    {'page': 'footer', 'section': 'brand', 'key': 'logo',
     'label': 'Footer Logo Image',
     'value': '/jynm_logo.png', 'content_type': 'image'},
    {'page': 'footer', 'section': 'brand', 'key': 'description',
     'label': 'Footer Brand Description',
     'value': "The nation's most trusted marketplace for verified used auto parts. Connecting mechanics and enthusiasts with salvage yards nationwide.",
     'content_type': 'textarea'},
    {'page': 'footer', 'section': 'brand', 'key': 'copyright',
     'label': 'Copyright Text',
     'value': '© 2025 JunkyardsNearMe. All rights reserved.', 'content_type': 'text'},

    {'page': 'footer', 'section': 'contact', 'key': 'phone',
     'label': 'Footer Phone Number',
     'value': '1-866-293-3731', 'content_type': 'text'},
    {'page': 'footer', 'section': 'contact', 'key': 'email',
     'label': 'Footer Email Address',
     'value': 'info@jynm.com', 'content_type': 'text'},
    {'page': 'footer', 'section': 'contact', 'key': 'address',
     'label': 'Footer Address',
     'value': '123 Salvage Lane, Phoenix AZ 85001', 'content_type': 'text'},

    {'page': 'footer', 'section': 'columns', 'key': 'quick_links_heading',
     'label': 'Quick Links Column Heading',
     'value': 'Quick Links', 'content_type': 'text'},
    {'page': 'footer', 'section': 'columns', 'key': 'resources_heading',
     'label': 'Resources Column Heading',
     'value': 'Resources', 'content_type': 'text'},
    {'page': 'footer', 'section': 'columns', 'key': 'contact_heading',
     'label': 'Contact Column Heading',
     'value': 'Contact', 'content_type': 'text'},

    {'page': 'footer', 'section': 'social', 'key': 'facebook',
     'label': 'Facebook URL',
     'value': 'https://www.facebook.com/JunkYardsNearMe', 'content_type': 'url'},
    {'page': 'footer', 'section': 'social', 'key': 'twitter',
     'label': 'Twitter / X URL',
     'value': 'https://x.com/junkyardsnearme', 'content_type': 'url'},
    {'page': 'footer', 'section': 'social', 'key': 'pinterest',
     'label': 'Pinterest URL',
     'value': 'https://www.pinterest.com/junkyardsnearme/', 'content_type': 'url'},
    {'page': 'footer', 'section': 'social', 'key': 'instagram',
     'label': 'Instagram URL',
     'value': 'https://www.instagram.com/junkyardsnearme/', 'content_type': 'url'},

    # ══════════════════════════════════════════════════════════════════
    # GLOBAL / SHARED
    # ══════════════════════════════════════════════════════════════════

    {'page': 'global', 'section': 'seo', 'key': 'site_name',
     'label': 'Site Name',
     'value': 'JunkyardsNearMe', 'content_type': 'text'},
    {'page': 'global', 'section': 'seo', 'key': 'og_image',
     'label': 'Default OG/Social Share Image',
     'value': '/jynm_logo.png', 'content_type': 'image'},
    {'page': 'global', 'section': 'announcements', 'key': 'banner_text',
     'label': 'Top Banner Announcement (leave empty to hide)',
     'value': '', 'content_type': 'text'},
    {'page': 'global', 'section': 'announcements', 'key': 'banner_link',
     'label': 'Top Banner Link',
     'value': '', 'content_type': 'url'},

    # ══════════════════════════════════════════════════════════════════
    # ADD A YARD PAGE
    # ══════════════════════════════════════════════════════════════════
    {'page': 'add_a_yard', 'section': 'header', 'key': 'title',
     'label': 'Page Title', 'value': 'Vendor Onboarding', 'content_type': 'text'},
    {'page': 'add_a_yard', 'section': 'header', 'key': 'subtitle',
     'label': 'Page Subtitle', 'value': 'Join thousands of yards expanding their business online.', 'content_type': 'text'},

    {'page': 'add_a_yard', 'section': 'success', 'key': 'title',
     'label': 'Success Screen Title', 'value': 'Application Submitted!', 'content_type': 'text'},
    {'page': 'add_a_yard', 'section': 'success', 'key': 'message',
     'label': 'Success Screen Message', 'value': 'Thank you for joining our platform. You will be able to manage your Premium Ads and inventory from your Dashboard once approved.', 'content_type': 'textarea'},
    {'page': 'add_a_yard', 'section': 'success', 'key': 'btn_home',
     'label': 'Success Button: Home', 'value': 'Back to Home', 'content_type': 'text'},
    {'page': 'add_a_yard', 'section': 'success', 'key': 'btn_login',
     'label': 'Success Button: Login', 'value': 'Go to Vendor Login', 'content_type': 'text'},

    {'page': 'add_a_yard', 'section': 'steps', 'key': 'step1_title',
     'label': 'Step 1 Title', 'value': 'Basic Info', 'content_type': 'text'},
    {'page': 'add_a_yard', 'section': 'steps', 'key': 'step1_subtitle',
     'label': 'Step 1 Subtitle', 'value': 'Create your profile', 'content_type': 'text'},
    {'page': 'add_a_yard', 'section': 'steps', 'key': 'step2_title',
     'label': 'Step 2 Title', 'value': 'Location', 'content_type': 'text'},
    {'page': 'add_a_yard', 'section': 'steps', 'key': 'step2_subtitle',
     'label': 'Step 2 Subtitle', 'value': 'Where are you located?', 'content_type': 'text'},
    {'page': 'add_a_yard', 'section': 'steps', 'key': 'step3_title',
     'label': 'Step 3 Title', 'value': 'Services', 'content_type': 'text'},
    {'page': 'add_a_yard', 'section': 'steps', 'key': 'step3_subtitle',
     'label': 'Step 3 Subtitle', 'value': 'Business offerings', 'content_type': 'text'},
    {'page': 'add_a_yard', 'section': 'steps', 'key': 'step4_title',
     'label': 'Step 4 Title', 'value': 'Review', 'content_type': 'text'},
    {'page': 'add_a_yard', 'section': 'steps', 'key': 'step4_subtitle',
     'label': 'Step 4 Subtitle', 'value': 'Final check', 'content_type': 'text'},

    {'page': 'add_a_yard', 'section': 'controls', 'key': 'btn_back',
     'label': 'Back Button Text', 'value': 'Back', 'content_type': 'text'},
    {'page': 'add_a_yard', 'section': 'controls', 'key': 'btn_continue',
     'label': 'Continue Button Text', 'value': 'Continue', 'content_type': 'text'},
    {'page': 'add_a_yard', 'section': 'controls', 'key': 'btn_submit',
     'label': 'Submit Button Text', 'value': 'Submit Application', 'content_type': 'text'},

    # ══════════════════════════════════════════════════════════════════
    # VENDOR PORTAL
    # ══════════════════════════════════════════════════════════════════
    {'page': 'vendor_portal', 'section': 'ads', 'key': 'ad_plans',
     'label': 'Ad Plans Configuration (JSON format)',
     'value': '[\n  {\n    "id": "minimal",\n    "name": "Minimal Plan",\n    "price": 49,\n    "color": "from-slate-600 to-slate-500",\n    "popular": false,\n    "features": ["Basic Visibility", "Standard Support"]\n  },\n  {\n    "id": "standard",\n    "name": "Standard Plan",\n    "price": 99,\n    "color": "from-blue-600 to-teal-600",\n    "popular": false,\n    "features": ["Featured Results", "High Priority Support"]\n  },\n  {\n    "id": "compact",\n    "name": "Compact Plan",\n    "price": 149,\n    "color": "from-purple-600 to-pink-500",\n    "popular": false,\n    "features": ["Highlighted Results", "Premium Badge"]\n  },\n  {\n    "id": "premium",\n    "name": "Premium Plan",\n    "price": 199,\n    "color": "from-yellow-400 to-orange-500",\n    "popular": true,\n    "features": ["Top #1 Placement", "Gold Styling", "Guaranteed Traffic"]\n  }\n]',
     'content_type': 'json'},
    {'page': 'vendor_portal', 'section': 'ads', 'key': 'header_title',
     'label': 'Ads Header Title (HTML)',
     'value': 'Marketplace <span class="vendor-gradient-text ml-2">Advertising</span>', 'content_type': 'html'},
    {'page': 'vendor_portal', 'section': 'ads', 'key': 'header_desc',
     'label': 'Ads Header Description',
     'value': 'Boost your yard\'s visibility globally and dominate the search results.', 'content_type': 'textarea'},

    {'page': 'vendor_portal', 'section': 'dashboard', 'key': 'welcome_text',
     'label': 'Dashboard Welcome Title',
     'value': 'Welcome back!', 'content_type': 'text'},
    {'page': 'vendor_portal', 'section': 'dashboard', 'key': 'help_text',
     'label': 'Dashboard Help Subtext',
     'value': 'Manage your parts inventory, track views, and publish ads directly.', 'content_type': 'textarea'},
]
