# Generated by Django 5.2.8 on 2026-01-13 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hollander", "0009_vendor_description_vendor_is_featured_and_more"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendorprofile",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profiles",
                to="hollander.vendor",
            ),
        ),
    ]
