# Generated by Django 5.0 on 2026-01-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='can_manage_inventory',
            field=models.BooleanField(default=True, help_text='Can manage vendor inventory'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='last_login_ip',
            field=models.CharField(blank=True, help_text='Last login IP for security', max_length=45),
        ),
    ]
