# Generated by Django 5.2.8 on 2026-01-16 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_vendorprofile_vendor"),
        ("users", "0002_vendorprofile_can_manage_inventory_and_more"),
    ]

    operations = []
