# Generated by Django 5.0 on 2026-01-14 14:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0003_lead_hollander_number_lead_options_lead_state_and_more'),
        ('vendors', '0006_vendor_inventory_preferences_vendor_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorBusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('is_open', models.BooleanField(default=True)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='vendors.vendor')),
            ],
            options={
                'db_table': 'vendor_business_hours',
                'ordering': ['vendor', 'day_of_week'],
                'unique_together': {('vendor', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='VendorInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('make', 'Make'), ('model', 'Model'), ('part', 'Part')], max_length=10)),
                ('make', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('part_name', models.CharField(blank=True, max_length=200)),
                ('year_start', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('year_end', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('is_available', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='vendors.vendor')),
            ],
            options={
                'db_table': 'vendor_inventory',
                'ordering': ['make', 'model', 'part_name'],
                'indexes': [models.Index(fields=['vendor', 'item_type'], name='vendor_inve_vendor__8541c6_idx'), models.Index(fields=['make'], name='vendor_inve_make_e887c0_idx'), models.Index(fields=['is_available'], name='vendor_inve_is_avai_51f655_idx')],
            },
        ),
        migrations.CreateModel(
            name='VendorNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_lead', 'New Lead'), ('lead_update', 'Lead Update'), ('system', 'System Notification'), ('account', 'Account Notification')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='vendors.vendor')),
            ],
            options={
                'db_table': 'vendor_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor', 'is_read'], name='vendor_noti_vendor__401ec6_idx'), models.Index(fields=['created_at'], name='vendor_noti_created_3497aa_idx')],
            },
        ),
    ]
