# Generated by Django 5.2.8 on 2026-01-21 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0008_alter_vendorlead_options_remove_vendorlead_source_and_more"),
        ("vendor_portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendornotification",
            name="vendor_lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="leads.vendorlead",
            ),
        ),
    ]
