# Generated by Django 5.0 on 2025-12-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=500)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=50)),
                ("zipcode", models.CharField(max_length=20)),
                ("description", models.TextField(blank=True)),
                ("review_snippet", models.TextField(blank=True)),
                ("rating", models.CharField(default="100%", max_length=20)),
                ("profile_url", models.CharField(max_length=255)),
                (
                    "logo",
                    models.CharField(
                        default="/images/logo-placeholder.png", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["state"], name="vendors_ven_state_a9d08e_idx"),
                    models.Index(fields=["city"], name="vendors_ven_city_4e1b89_idx"),
                    models.Index(
                        fields=["zipcode"], name="vendors_ven_zipcode_5bf92a_idx"
                    ),
                ],
            },
        ),
    ]
