# Generated by Django 5.2.8 on 2025-12-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vendor",
            options={"ordering": ["id"]},
        ),
        migrations.AddField(
            model_name="vendor",
            name="is_trusted",
            field=models.BooleanField(
                default=False, help_text="Mark as trusted vendor for premium display"
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="trust_level",
            field=models.IntegerField(
                default=0, help_text="Priority level (higher = more prominent)"
            ),
        ),
    ]
