# Generated by Django 5.0 on 2025-12-22 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_alter_vendor_options_vendor_is_trusted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='is_trusted',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='trust_level',
        ),
    ]
