# Generated by Django 5.0 on 2025-12-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_remove_vendor_is_trusted_remove_vendor_trust_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_trusted',
            field=models.BooleanField(default=False, help_text='Mark as trusted vendor for premium display'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='trust_level',
            field=models.IntegerField(default=0, help_text='Priority level (higher = more prominent)'),
        ),
    ]
