# Generated by Django 5.0 on 2025-12-30 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_vendor_is_trusted_vendor_trust_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Display Featured badge'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_top_rated',
            field=models.BooleanField(default=False, help_text='Display Top Rated badge'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='rating_percentage',
            field=models.IntegerField(default=100, help_text='Rating percentage (0-100%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='vendor',
            name='rating_stars',
            field=models.IntegerField(default=5, help_text='Star rating (1-5 stars)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
