# Generated by Django 5.2.8 on 2026-01-13 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0005_vendor_is_featured_vendor_is_top_rated_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Vendor",
        ),
    ]
