# Generated by Django 5.0 on 2026-01-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendor_is_featured_vendor_is_top_rated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='inventory_preferences',
            field=models.JSONField(blank=True, default=dict, help_text='Inventory management settings'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Vendor account active status'),
        ),
    ]
