# Generated by Django 5.2.8 on 2025-12-22 20:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "slot",
                    models.CharField(
                        choices=[
                            ("left_sidebar_ad", "Left Sidebar Ad"),
                            ("right_sidebar_ad", "Right Sidebar Ad"),
                        ],
                        max_length=50,
                    ),
                ),
                ("image", models.ImageField(upload_to="ads/")),
                (
                    "redirect_url",
                    models.URLField(help_text="URL to redirect to when clicked"),
                ),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Higher number = higher priority"
                    ),
                ),
                ("clicks", models.PositiveIntegerField(default=0)),
                ("impressions", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-priority", "-created_at"],
            },
        ),
    ]
