# Generated by Django 5.2.8 on 2025-12-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="page",
            field=models.CharField(
                choices=[
                    ("all", "All Pages"),
                    ("home", "Home Page"),
                    ("vendors", "Vendors Page"),
                    ("browse", "Browse Page"),
                ],
                default="all",
                help_text="Select which page this ad appears on",
                max_length=50,
            ),
        ),
    ]
