# Generated by Django 5.0 on 2025-12-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_advertisement_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="button_text",
            field=models.CharField(
                blank=True,
                default="Visit Website",
                help_text="Custom text for the main button",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="show_badge",
            field=models.BooleanField(
                default=True, help_text="Show 'Featured' badge at top of ad"
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("standard", "Standard Template"),
                    ("minimal", "Minimal Template"),
                    ("premium", "Premium Template"),
                    ("compact", "Compact Template"),
                ],
                default="standard",
                help_text="Choose the visual style for this ad",
                max_length=20,
            ),
        ),
    ]
