# Generated by Django 5.2.8 on 2026-02-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0004_alter_advertisement_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
