# Generated by Django 5.0 on 2026-06-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_advertisement_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='page',
            field=models.CharField(choices=[('all', 'All Pages'), ('home', 'Home Page'), ('vendors', 'Vendors Page'), ('browse', 'Browse Page'), ('about', 'About Page'), ('contact', 'Contact Page'), ('blog', 'Blog Page'), ('faq', 'FAQ Page')], default='all', help_text='Select which page this ad appears on', max_length=50),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='slot',
            field=models.CharField(choices=[('left_sidebar_ad', 'Left Sidebar Ad'), ('right_sidebar_ad', 'Right Sidebar Ad'), ('strip_top', 'Strip — Top (below hero)'), ('strip_bottom', 'Strip — Bottom (before footer)'), ('strip_home_mid', 'Strip — Home Middle')], max_length=50),
        ),
    ]
