# Generated by Django 5.1.4 on 2026-06-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0007_alter_advertisement_slot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="slot",
            field=models.CharField(
                choices=[
                    ("strip_top", "Strip — Top (below hero)"),
                    ("strip_bottom", "Strip — Bottom (before footer)"),
                    ("strip_home_mid", "Strip — Home Middle"),
                    ("carousel_1", "Carousel Slider 1 (Top)"),
                    ("carousel_2", "Carousel Slider 2"),
                    ("carousel_3", "Carousel Slider 3 (Middle)"),
                    ("carousel_4", "Carousel Slider 4"),
                    ("carousel_5", "Carousel Slider 5 (Bottom)"),
                ],
                max_length=50,
            ),
        ),
    ]
