# Generated by Django 5.2.13 on 2026-04-16 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file", models.ImageField(blank=True, upload_to="cms/media/")),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="External URL if hosted on Azure/CDN",
                        max_length=500,
                    ),
                ),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="media_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cms_media_assets",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        choices=[
                            ("home", "Home"),
                            ("about", "About"),
                            ("contact", "Contact"),
                            ("browse", "Browse States"),
                            ("blog", "Blog"),
                            ("vendors", "Vendors Listing"),
                            ("faq", "FAQ"),
                            ("how_it_works", "How It Works"),
                            ("navbar", "Navbar (Global)"),
                            ("footer", "Footer (Global)"),
                            ("seo_home", "SEO – Home"),
                            ("seo_about", "SEO – About"),
                            ("seo_contact", "SEO – Contact"),
                            ("seo_browse", "SEO – Browse"),
                            ("seo_blog", "SEO – Blog"),
                            ("seo_vendors", "SEO – Vendors"),
                        ],
                        db_index=True,
                        max_length=60,
                    ),
                ),
                ("section", models.CharField(db_index=True, max_length=100)),
                ("key", models.CharField(max_length=100)),
                ("value", models.TextField(blank=True, default="")),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("text", "Plain Text"),
                            ("html", "HTML"),
                            ("url", "URL / Link"),
                            ("boolean", "Boolean (visible/hidden)"),
                            ("image", "Image URL"),
                            ("json", "JSON Array"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable label for the CMS UI",
                        max_length=200,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cms_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Content",
                "verbose_name_plural": "Site Content",
                "db_table": "cms_site_content",
                "ordering": ["page", "section", "key"],
                "unique_together": {("page", "section", "key")},
            },
        ),
    ]
