# Generated by Django 5.0 on 2026-04-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitecontent",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("text", "Plain Text"),
                    ("textarea", "Long Text / Paragraph"),
                    ("html", "HTML"),
                    ("url", "URL / Link"),
                    ("boolean", "Boolean (visible/hidden)"),
                    ("image", "Image URL"),
                    ("json", "JSON Array"),
                ],
                default="text",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sitecontent",
            name="page",
            field=models.CharField(
                choices=[
                    ("home", "Home"),
                    ("about", "About"),
                    ("contact", "Contact"),
                    ("browse", "Browse States"),
                    ("blog", "Blog"),
                    ("vendors", "Vendors Listing"),
                    ("faq", "FAQ"),
                    ("how_it_works", "How It Works"),
                    ("navbar", "Navbar (Global)"),
                    ("footer", "Footer (Global)"),
                    ("global", "Global / Shared"),
                    ("seo_home", "SEO – Home"),
                    ("seo_about", "SEO – About"),
                    ("seo_contact", "SEO – Contact"),
                    ("seo_browse", "SEO – Browse"),
                    ("seo_blog", "SEO – Blog"),
                    ("seo_vendors", "SEO – Vendors"),
                ],
                db_index=True,
                max_length=60,
            ),
        ),
    ]
