# Generated by Django 5.0 on 2026-04-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_add_textarea_type_and_global_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitecontent",
            name="page",
            field=models.CharField(
                choices=[
                    ("home", "Home"),
                    ("about", "About"),
                    ("contact", "Contact"),
                    ("browse", "Browse States"),
                    ("blog", "Blog"),
                    ("vendors", "Vendors Listing"),
                    ("faq", "FAQ"),
                    ("how_it_works", "How It Works"),
                    ("navbar", "Navbar (Global)"),
                    ("footer", "Footer (Global)"),
                    ("global", "Global / Shared"),
                    ("add_a_yard", "Add a Yard"),
                    ("vendor_portal", "Vendor Portal"),
                    ("seo_home", "SEO – Home"),
                    ("seo_about", "SEO – About"),
                    ("seo_contact", "SEO – Contact"),
                    ("seo_browse", "SEO – Browse"),
                    ("seo_blog", "SEO – Blog"),
                    ("seo_vendors", "SEO – Vendors"),
                ],
                db_index=True,
                max_length=60,
            ),
        ),
    ]
