# Generated by Django 5.2.8 on 2025-12-23 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vendors", "0002_alter_vendor_options_vendor_is_trusted_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="YardSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(
                        help_text="Junkyard/Business name", max_length=255
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        help_text="Primary contact person", max_length=255
                    ),
                ),
                ("email", models.EmailField(help_text="Contact email", max_length=254)),
                (
                    "phone",
                    models.CharField(help_text="Contact phone number", max_length=20),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, help_text="Business website (optional)"
                    ),
                ),
                (
                    "address",
                    models.CharField(help_text="Street address", max_length=500),
                ),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=50)),
                ("zip_code", models.CharField(max_length=20)),
                (
                    "services",
                    models.TextField(
                        help_text="Services offered (e.g., Auto parts, Towing, Recycling)"
                    ),
                ),
                ("brands", models.TextField(help_text="Vehicle makes/brands serviced")),
                (
                    "parts_categories",
                    models.TextField(blank=True, help_text="Types of parts available"),
                ),
                ("description", models.TextField(help_text="Business description")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Business logo",
                        null=True,
                        upload_to="submissions/logos/",
                    ),
                ),
                (
                    "images",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Additional yard images (paths)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, help_text="Internal admin notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, help_text="When admin reviewed", null=True
                    ),
                ),
                (
                    "reviewed_by",
                    models.CharField(
                        blank=True, help_text="Admin who reviewed", max_length=255
                    ),
                ),
                (
                    "created_vendor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vendor created from this submission",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submission",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yard Submission",
                "verbose_name_plural": "Yard Submissions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="yard_submis_status_7a38ba_idx",
                    ),
                    models.Index(fields=["email"], name="yard_submis_email_1d2c4a_idx"),
                    models.Index(
                        fields=["zip_code"], name="yard_submis_zip_cod_b8f6be_idx"
                    ),
                ],
            },
        ),
    ]
