# Generated by Django 5.2.8 on 2025-12-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yard_submissions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="yardsubmission",
            name="business_hours",
            field=models.JSONField(
                blank=True, default=dict, help_text="Business hours by day"
            ),
        ),
        migrations.AddField(
            model_name="yardsubmission",
            name="country",
            field=models.CharField(default="United States", max_length=100),
        ),
        migrations.AddField(
            model_name="yardsubmission",
            name="fax",
            field=models.CharField(blank=True, help_text="Fax number", max_length=20),
        ),
        migrations.AddField(
            model_name="yardsubmission",
            name="owner_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="yardsubmission",
            name="owner_first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="yardsubmission",
            name="owner_last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="yardsubmission",
            name="owner_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="yardsubmission",
            name="payment_methods",
            field=models.JSONField(
                blank=True, default=list, help_text="Accepted payment methods"
            ),
        ),
        migrations.AddField(
            model_name="yardsubmission",
            name="subscription_plan",
            field=models.CharField(
                choices=[
                    ("standard", "Standard Plan - Basic Listing"),
                    ("minimal", "Minimal Plan - Clean & Simple"),
                    ("premium", "Premium Plan - Featured Listing"),
                    ("compact", "Compact Plan - Quick View"),
                ],
                default="standard",
                help_text="Selected advertising plan",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="yardsubmission",
            name="toll_free",
            field=models.CharField(
                blank=True, help_text="Toll free number", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="yardsubmission",
            name="phone",
            field=models.CharField(help_text="Local phone number", max_length=20),
        ),
    ]
