# Generated by Django 5.2.8 on 2026-01-13 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hollander", "0009_vendor_description_vendor_is_featured_and_more"),
        (
            "yard_submissions",
            "0002_yardsubmission_business_hours_yardsubmission_country_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="yardsubmission",
            name="created_vendor",
            field=models.ForeignKey(
                blank=True,
                help_text="Vendor created from this submission",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submission",
                to="hollander.vendor",
            ),
        ),
    ]
