# Generated by Django 5.0 on 2026-07-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard_submissions', '0003_alter_yardsubmission_created_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='yardsubmission',
            name='payment_status',
            field=models.CharField(choices=[('none', 'No Payment Required (Free)'), ('pending', 'Payment Pending'), ('paid', 'Paid'), ('failed', 'Payment Failed')], default='pending', help_text='Status of the Authorize.net transaction', max_length=20),
        ),
        migrations.AlterField(
            model_name='yardsubmission',
            name='subscription_plan',
            field=models.CharField(choices=[('standard', 'Standard Plan - Basic Listing'), ('minimal', 'Minimal Plan - Clean & Simple'), ('premium', 'Premium Plan - $49/mo'), ('compact', 'Compact Plan - Quick View'), ('free', 'Free Plan - $0/mo'), ('featured', 'Featured Plan - $99/mo')], default='free', help_text='Selected subscription plan', max_length=20),
        ),
    ]
