# Generated by Django 5.2.13 on 2026-04-16 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "color",
                    models.CharField(
                        default="#6366f1",
                        help_text="Hex color for UI badge",
                        max_length=20,
                    ),
                ),
                (
                    "can_manage_cms",
                    models.BooleanField(
                        default=False, help_text="Create/edit all CMS content"
                    ),
                ),
                (
                    "can_manage_vendors",
                    models.BooleanField(
                        default=False, help_text="View/edit vendor profiles"
                    ),
                ),
                (
                    "can_manage_leads",
                    models.BooleanField(
                        default=False, help_text="View/manage customer leads"
                    ),
                ),
                (
                    "can_manage_ads",
                    models.BooleanField(
                        default=False, help_text="Create/manage ad campaigns"
                    ),
                ),
                (
                    "can_manage_blog",
                    models.BooleanField(
                        default=False, help_text="Write/publish blog posts"
                    ),
                ),
                (
                    "can_manage_messages",
                    models.BooleanField(
                        default=False, help_text="Read/respond to messages"
                    ),
                ),
                (
                    "can_manage_yard_submissions",
                    models.BooleanField(
                        default=False, help_text="Review yard submissions"
                    ),
                ),
                (
                    "can_manage_settings",
                    models.BooleanField(
                        default=False, help_text="Change site-wide settings"
                    ),
                ),
                (
                    "can_manage_roles",
                    models.BooleanField(
                        default=False,
                        help_text="Create roles, invite staff — Admin only",
                    ),
                ),
                (
                    "can_view_only",
                    models.BooleanField(
                        default=False,
                        help_text="Read-only across all permitted modules",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "rbac_staff_roles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StaffMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invited_staff",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="rbac.staffrole",
                    ),
                ),
            ],
            options={
                "db_table": "rbac_staff_members",
                "ordering": ["-created_at"],
            },
        ),
    ]
