# Generated by Django 5.2.8 on 2026-01-06 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Make",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make_id", models.IntegerField(unique=True)),
                ("make_name", models.CharField(db_index=True, max_length=100)),
            ],
            options={
                "db_table": "hollander_make",
                "ordering": ["make_name"],
            },
        ),
        migrations.CreateModel(
            name="PartType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_id", models.IntegerField(unique=True)),
                ("part_name", models.CharField(db_index=True, max_length=200)),
            ],
            options={
                "db_table": "hollander_part_type",
                "ordering": ["part_name"],
            },
        ),
        migrations.CreateModel(
            name="HollanderInterchange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hollander_number", models.CharField(db_index=True, max_length=50)),
                ("year_start", models.IntegerField(default=0)),
                ("year_end", models.IntegerField(default=0)),
                (
                    "make",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                (
                    "part_type",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                ("part_name", models.CharField(blank=True, default="", max_length=200)),
                ("options", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                ("mfr_code", models.CharField(blank=True, default="", max_length=10)),
                (
                    "part_type_number",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "hollander_interchange",
                "ordering": ["hollander_number"],
                "indexes": [
                    models.Index(
                        fields=["year_start", "year_end", "make", "model", "part_type"],
                        name="hollander_i_year_st_732ce1_idx",
                    ),
                    models.Index(
                        fields=["hollander_number", "part_type"],
                        name="hollander_i_holland_1f8220_idx",
                    ),
                    models.Index(
                        fields=["make", "model"], name="hollander_i_make_1eeaef_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_id", models.IntegerField(unique=True)),
                ("model_name", models.CharField(db_index=True, max_length=100)),
                (
                    "make",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="hollander.make",
                        to_field="make_id",
                    ),
                ),
            ],
            options={
                "db_table": "hollander_model",
                "ordering": ["model_name"],
            },
        ),
        migrations.CreateModel(
            name="PartPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hollander_number", models.CharField(db_index=True, max_length=50)),
                ("make", models.CharField(blank=True, default="", max_length=100)),
                ("model", models.CharField(blank=True, default="", max_length=100)),
                ("part_name", models.CharField(blank=True, default="", max_length=200)),
                ("year_start", models.IntegerField(default=0)),
                ("year_end", models.IntegerField(default=0)),
                (
                    "new_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "wow_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "cts_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("option1", models.CharField(blank=True, default="", max_length=200)),
                ("option2", models.CharField(blank=True, default="", max_length=200)),
                ("option3", models.CharField(blank=True, default="", max_length=200)),
                ("option4", models.CharField(blank=True, default="", max_length=200)),
                ("option5", models.CharField(blank=True, default="", max_length=200)),
                ("option6", models.CharField(blank=True, default="", max_length=200)),
                ("option7", models.CharField(blank=True, default="", max_length=200)),
                ("option8", models.CharField(blank=True, default="", max_length=200)),
                ("option9", models.CharField(blank=True, default="", max_length=200)),
                ("option10", models.CharField(blank=True, default="", max_length=200)),
                ("option11", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "hollander_part_pricing",
                "ordering": ["hollander_number"],
                "indexes": [
                    models.Index(
                        fields=["hollander_number"],
                        name="hollander_p_holland_e5eb4c_idx",
                    ),
                    models.Index(
                        fields=["make", "model", "part_name"],
                        name="hollander_p_make_0cd0d9_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PartSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specification_name", models.CharField(max_length=200)),
                ("specification_value", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pricing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specifications",
                        to="hollander.partpricing",
                    ),
                ),
            ],
            options={
                "db_table": "hollander_part_specification",
                "ordering": ["specification_name"],
            },
        ),
        migrations.CreateModel(
            name="YearRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_start", models.IntegerField()),
                ("year_end", models.IntegerField()),
                (
                    "make",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="year_ranges",
                        to="hollander.make",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="year_ranges",
                        to="hollander.model",
                    ),
                ),
            ],
            options={
                "db_table": "hollander_year_range",
            },
        ),
        migrations.AddIndex(
            model_name="model",
            index=models.Index(
                fields=["make", "model_name"], name="hollander_m_make_id_22fd0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="yearrange",
            index=models.Index(
                fields=["make", "model"], name="hollander_y_make_id_85ed06_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="yearrange",
            unique_together={("make", "model")},
        ),
    ]
