# Generated by Django 5.2.8 on 2026-01-06 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hollander", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "yard_id",
                    models.IntegerField(
                        help_text="Legacy ID from _yard.json", unique=True
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(blank=True, default="", max_length=255)),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("state", models.CharField(blank=True, default="", max_length=10)),
                ("zip_code", models.CharField(blank=True, default="", max_length=20)),
                ("phone", models.CharField(blank=True, default="", max_length=50)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("website", models.URLField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "hollander_vendor",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="partpricing",
            name="make_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pricing",
                to="hollander.make",
            ),
        ),
        migrations.AddField(
            model_name="partpricing",
            name="model_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pricing",
                to="hollander.model",
            ),
        ),
        migrations.AddField(
            model_name="partpricing",
            name="part_type_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pricing",
                to="hollander.parttype",
            ),
        ),
        migrations.AddField(
            model_name="partpricing",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pricing",
                to="hollander.vendor",
            ),
        ),
    ]
