# Generated by Django 5.2.8 on 2026-01-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "hollander",
            "0002_vendor_partpricing_make_ref_partpricing_model_ref_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="HollanderMakeModelRef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ref_id", models.IntegerField(unique=True)),
                ("h_make_code", models.CharField(max_length=50)),
                ("h_make", models.CharField(max_length=100)),
                ("h_model", models.CharField(max_length=100)),
                ("aph_make", models.CharField(blank=True, max_length=100)),
                ("aph_model", models.CharField(blank=True, max_length=100)),
                ("a_url", models.CharField(blank=True, max_length=200)),
                ("active_flag", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "hollander_make_model_ref",
            },
        ),
        migrations.CreateModel(
            name="HollanderPartRef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vpid", models.IntegerField(unique=True)),
                ("part_code", models.CharField(max_length=50)),
                ("part_name", models.CharField(max_length=200)),
                ("part_url", models.CharField(blank=True, max_length=200)),
                ("part_kw", models.CharField(blank=True, max_length=200)),
                ("active_flag", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "hollander_part_ref",
            },
        ),
        migrations.CreateModel(
            name="VehicleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_id", models.IntegerField(unique=True)),
                ("image_target_id", models.IntegerField(db_index=True)),
                ("image_category_id", models.IntegerField()),
                ("image_file_name", models.CharField(max_length=255)),
                ("image_title", models.CharField(blank=True, max_length=255)),
                ("image_created_on", models.DateTimeField(blank=True, null=True)),
                ("image_deleted", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "hollander_vehicle_image",
            },
        ),
        migrations.CreateModel(
            name="HollanderIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idx_id", models.CharField(db_index=True, max_length=50)),
                ("model_nm", models.CharField(db_index=True, max_length=50)),
                ("part_type_nbr", models.CharField(db_index=True, max_length=50)),
                ("mfr_cd", models.CharField(blank=True, max_length=50)),
                ("begin_year", models.IntegerField(default=0)),
                ("end_year", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "hollander_index",
                "indexes": [
                    models.Index(
                        fields=["idx_id"], name="hollander_i_idx_id_fac071_idx"
                    ),
                    models.Index(
                        fields=["model_nm", "part_type_nbr"],
                        name="hollander_i_model_n_e961bc_idx",
                    ),
                ],
            },
        ),
    ]
