# Generated by Django 5.2.8 on 2026-01-06 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "hollander",
            "0003_hollandermakemodelref_hollanderpartref_vehicleimage_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_code", models.CharField(max_length=5, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("country_id", models.IntegerField(default=1)),
            ],
            options={
                "db_table": "hollander_state",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="VendorDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_visa", models.BooleanField(default=False)),
                ("payment_mastercard", models.BooleanField(default=False)),
                ("payment_amex", models.BooleanField(default=False)),
                ("payment_discover", models.BooleanField(default=False)),
                ("payment_check", models.BooleanField(default=False)),
                ("in_business_since", models.IntegerField(default=0)),
                ("warranty_num", models.IntegerField(default=0)),
                ("warranty_type", models.IntegerField(default=0)),
                (
                    "vendor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="hollander.vendor",
                        to_field="yard_id",
                    ),
                ),
            ],
            options={
                "db_table": "hollander_vendor_detail",
            },
        ),
        migrations.CreateModel(
            name="VendorHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weekday_id", models.IntegerField()),
                ("open_time", models.CharField(blank=True, max_length=50)),
                ("close_time", models.CharField(blank=True, max_length=50)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hours",
                        to="hollander.vendor",
                        to_field="yard_id",
                    ),
                ),
            ],
            options={
                "db_table": "hollander_vendor_hours",
            },
        ),
        migrations.CreateModel(
            name="VendorRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate_id", models.IntegerField(unique=True)),
                ("service_score", models.IntegerField(default=0)),
                ("quality_score", models.IntegerField(default=0)),
                ("price_score", models.IntegerField(default=0)),
                ("comment", models.TextField(blank=True)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("zip_code", models.CharField(blank=True, max_length=20)),
                ("date_posted", models.CharField(blank=True, max_length=50)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="hollander.vendor",
                        to_field="yard_id",
                    ),
                ),
            ],
            options={
                "db_table": "hollander_vendor_rating",
            },
        ),
        migrations.CreateModel(
            name="Zipcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zipcode_id", models.IntegerField(unique=True)),
                ("postal_code", models.CharField(db_index=True, max_length=20)),
                ("city_name", models.CharField(max_length=100)),
                ("state_abbr", models.CharField(db_index=True, max_length=5)),
                ("county_name", models.CharField(blank=True, max_length=100)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "hollander_zipcode",
                "indexes": [
                    models.Index(
                        fields=["postal_code"], name="hollander_z_postal__7c00c3_idx"
                    ),
                    models.Index(
                        fields=["city_name"], name="hollander_z_city_na_c5b384_idx"
                    ),
                ],
            },
        ),
    ]
