# Generated by Django 5.2.8 on 2026-01-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hollander", "0004_state_vendordetail_vendorhours_vendorrating_zipcode"),
    ]

    operations = [
        migrations.CreateModel(
            name="Association",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("association_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("url", models.CharField(blank=True, max_length=255)),
                ("state_code", models.CharField(blank=True, max_length=10)),
                ("country_code", models.CharField(blank=True, max_length=10)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "hollander_association",
            },
        ),
        migrations.CreateModel(
            name="LegacyAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_id", models.IntegerField(unique=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("profile_title", models.CharField(blank=True, max_length=255)),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("contact_phone", models.CharField(blank=True, max_length=50)),
                ("address_street1", models.CharField(blank=True, max_length=255)),
                ("address_city", models.CharField(blank=True, max_length=100)),
                ("address_state", models.CharField(blank=True, max_length=50)),
                ("address_zip", models.CharField(blank=True, max_length=20)),
                ("address_country", models.CharField(blank=True, max_length=50)),
                ("created_at", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "hollander_legacy_account",
            },
        ),
        migrations.CreateModel(
            name="LegacyUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(unique=True)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("password_hash", models.CharField(max_length=255)),
                ("password_salt", models.CharField(blank=True, max_length=255)),
                ("legacy_password_plain", models.CharField(blank=True, max_length=255)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "db_table": "hollander_legacy_user",
            },
        ),
    ]
