# Generated by Django 5.2.8 on 2026-01-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hollander", "0006_country_presetlocation_presetmake_presetmodel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tracking_id", models.BigIntegerField(unique=True)),
                ("account_id", models.IntegerField(db_index=True)),
                ("created_on", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "hollander_profile_visit",
                "ordering": ["-created_on"],
            },
        ),
    ]
