# Generated by Django 5.2.8 on 2026-01-07 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hollander", "0007_profilevisit"),
    ]

    operations = [
        migrations.CreateModel(
            name="YardMake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "make",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yards",
                        to="hollander.make",
                        to_field="make_id",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yard_makes",
                        to="hollander.vendor",
                        to_field="yard_id",
                    ),
                ),
            ],
            options={
                "db_table": "hollander_yard_make",
                "indexes": [
                    models.Index(
                        fields=["vendor", "make"], name="hollander_y_vendor__abee6b_idx"
                    )
                ],
                "unique_together": {("vendor", "make")},
            },
        ),
        migrations.CreateModel(
            name="YardPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "part_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yards",
                        to="hollander.parttype",
                        to_field="part_id",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yard_parts",
                        to="hollander.vendor",
                        to_field="yard_id",
                    ),
                ),
            ],
            options={
                "db_table": "hollander_yard_part",
                "indexes": [
                    models.Index(
                        fields=["vendor", "part_type"],
                        name="hollander_y_vendor__fb0c54_idx",
                    )
                ],
                "unique_together": {("vendor", "part_type")},
            },
        ),
    ]
