# Generated by Django 5.2.8 on 2026-01-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hollander", "0008_yardmake_yardpart"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="vendor",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vendor",
            name="is_top_rated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vendor",
            name="is_trusted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vendor",
            name="logo",
            field=models.CharField(
                default="/images/logo-placeholder.png", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="profile_url",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="vendor",
            name="rating",
            field=models.CharField(default="100%", max_length=20),
        ),
        migrations.AddField(
            model_name="vendor",
            name="rating_percentage",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="vendor",
            name="rating_stars",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="vendor",
            name="review_snippet",
            field=models.TextField(blank=True, default=""),
        ),
    ]
