# Generated by Django 5.2.8 on 2026-01-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hollander", "0009_vendor_description_vendor_is_featured_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="inventory_preferences",
            field=models.JSONField(
                blank=True, default=dict, help_text="Inventory management settings"
            ),
        ),
    ]
