# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hollander', '0010_vendor_inventory_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='logo_source',
            field=models.CharField(
                choices=[
                    ('matched', 'Matched'),
                    ('placeholder', 'Placeholder'),
                    ('manual', 'Manual')
                ],
                default='placeholder',
                max_length=20,
                help_text='Source of the vendor logo'
            ),
        ),
        migrations.AddField(
            model_name='vendor',
            name='logo_verified',
            field=models.BooleanField(
                default=False,
                help_text='Whether the logo assignment has been verified'
            ),
        ),
    ]
