# Generated by Django 5.0 on 2026-01-27 07:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hollander', '0010_vendor_inventory_preferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorImportBatch',
            fields=[
                ('batch_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('total_rows', models.IntegerField(default=0)),
                ('valid_rows', models.IntegerField(default=0)),
                ('invalid_rows', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vendor_import_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorImportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('skipped', 'Skipped'), ('failed', 'Failed')], max_length=20)),
                ('row_number', models.IntegerField()),
                ('previous_state', models.JSONField(blank=True, help_text='Vendor data before update (for rollback)', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='hollander.vendorimportbatch')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_records', to='hollander.vendor')),
            ],
            options={
                'db_table': 'vendor_import_record',
                'ordering': ['batch', 'row_number'],
                'indexes': [models.Index(fields=['batch', 'action'], name='vendor_impo_batch_i_f5d685_idx')],
            },
        ),
    ]
