# Generated by Django 5.2.8 on 2026-01-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hollander", "0011_add_logo_metadata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendor",
            name="logo_source",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="logo_verified",
        ),
        migrations.AlterField(
            model_name="vendor",
            name="logo",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="vendor_logos/"
            ),
        ),
    ]
