# Generated by Django 5.2.8 on 2026-01-28 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hollander", "0011_vendorimportbatch_vendorimportrecord"),
        ("hollander", "0012_remove_vendor_logo_source_and_more"),
    ]

    operations = []
