# Generated by Django 5.2.8 on 2026-02-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hollander", "0013_merge_20260128_1240"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="city",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="state",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="zip_code",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=20
            ),
        ),
    ]
