# Generated by Django 5.0 on 2026-04-14 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hollander', '0014_alter_vendor_city_alter_vendor_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('standard', 'Standard Plan'), ('minimal', 'Minimal Plan'), ('premium', 'Premium Plan'), ('compact', 'Compact Plan')], max_length=20)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='hollander.vendor', to_field='yard_id')),
            ],
            options={
                'db_table': 'hollander_vendor_ad',
                'ordering': ['-created_at'],
            },
        ),
    ]
