# Generated by Django 5.0 on 2026-04-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hollander', '0015_vendorad'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='trusted_vendor',
            field=models.BooleanField(default=False),
        ),
    ]
