# Generated by Django 5.0 on 2026-04-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hollander", "0016_vendor_trusted_vendor"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorad",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vendorad",
            name="transaction_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
