# Generated by Django 5.0 on 2026-04-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hollander", "0017_vendorad_payment_status_vendorad_transaction_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="profile_views",
            field=models.IntegerField(default=0),
        ),
    ]
