# Generated by Django 5.0 on 2026-07-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hollander', '0018_vendor_profile_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='brands',
            field=models.TextField(blank=True, default='', help_text='Brands specialized in'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text='Array of image URLs for the yard'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='services',
            field=models.TextField(blank=True, default='', help_text='Services/Parts offered (from submission/portal)'),
        ),
    ]
