# Generated by Django 5.2.8 on 2025-12-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="email",
            field=models.EmailField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="lead",
            name="location",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="lead",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="lead",
            name="phone",
            field=models.CharField(default="", max_length=20),
        ),
    ]
