# Generated by Django 5.2.8 on 2026-01-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_lead_email_lead_location_lead_name_lead_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="hollander_number",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="lead",
            name="options",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="lead",
            name="state",
            field=models.CharField(blank=True, default="", max_length=2),
        ),
        migrations.AddField(
            model_name="lead",
            name="zip",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="lead",
            name="location",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
