# Generated by Django 5.0 on 2026-01-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_hollander_number_lead_options_lead_state_and_more'),
        ('vendors', '0006_vendor_inventory_preferences_vendor_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='assigned_vendors',
            field=models.ManyToManyField(blank=True, help_text='Vendors this lead is assigned to', related_name='assigned_leads', to='vendors.vendor'),
        ),
    ]
