# Generated by Django 5.2.8 on 2026-01-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0004_add_vendor_assignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="lead_type",
            field=models.CharField(
                choices=[
                    ("quality_auto_parts", "Quality Auto Parts"),
                    ("vendor", "Junkyard Vendor"),
                ],
                default="quality_auto_parts",
                max_length=50,
            ),
        ),
    ]
