# Generated by Django 5.2.8 on 2026-01-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hollander", "0010_vendor_inventory_preferences"),
        ("leads", "0005_lead_lead_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lead",
            options={},
        ),
        migrations.RemoveField(
            model_name="lead",
            name="assigned_vendors",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="lead_type",
        ),
        migrations.CreateModel(
            name="VendorLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("state", models.CharField(max_length=2)),
                ("zip", models.CharField(max_length=10)),
                ("source", models.CharField(default="junkyard_vendor", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_vendors",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Vendors this lead is assigned to",
                        related_name="assigned_leads",
                        to="hollander.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
