# Generated by Django 5.2.8 on 2026-01-21 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hollander", "0010_vendor_inventory_preferences"),
        ("leads", "0006_alter_lead_options_remove_lead_assigned_vendors_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lead",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="vendorlead",
            name="assigned_vendors",
        ),
        migrations.RemoveField(
            model_name="vendorlead",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="lead",
            name="assigned_vendors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Vendors this lead is assigned to",
                related_name="assigned_leads",
                to="hollander.vendor",
            ),
        ),
    ]
