# Generated by Django 5.2.8 on 2026-01-21 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0007_alter_lead_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vendorlead",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Vendor Lead",
                "verbose_name_plural": "Vendor Leads",
            },
        ),
        migrations.RemoveField(
            model_name="vendorlead",
            name="source",
        ),
        migrations.AddField(
            model_name="lead",
            name="lead_type",
            field=models.CharField(
                choices=[
                    ("quality_auto_parts", "Quality Auto Parts"),
                    ("vendor", "Junkyard Vendor"),
                ],
                default="quality_auto_parts",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="vendorlead",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("contacted", "Contacted"),
                    ("converted", "Converted"),
                    ("closed", "Closed"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vendorlead",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
