# Generated by Django 5.2.8 on 2026-01-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0008_alter_vendorlead_options_remove_vendorlead_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="notification_sent",
            field=models.BooleanField(
                default=False, help_text="Whether email notification has been sent"
            ),
        ),
    ]
