# Generated by Django 5.2.8 on 2026-01-30 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0009_lead_notification_sent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lead",
            name="assigned_vendors",
        ),
    ]
