# Generated by Django 5.2.8 on 2026-02-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0010_remove_lead_assigned_vendors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("contacted", "Contacted"),
                    ("converted", "Converted"),
                    ("closed", "Closed"),
                ],
                db_index=True,
                default="new",
                max_length=20,
            ),
        ),
    ]
