# Generated by Django 5.0 on 2026-04-14 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hollander', '0015_vendorad'),
        ('leads', '0011_alter_lead_created_at_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Assigned vendor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='hollander.vendor'),
        ),
    ]
