# Generated by Django 5.1.4 on 2026-07-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0012_lead_vendor"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="hollander_candidates",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="All candidate HNs when exact resolution not possible",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="options",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
