# Generated by Django 5.0 on 2026-09-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_add_hollander_candidates'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(blank=True, default='', max_length=17)),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('trim', models.CharField(blank=True, default='', max_length=100)),
                ('mileage', models.CharField(blank=True, default='', max_length=50)),
                ('drivable', models.BooleanField(default=False)),
                ('has_title', models.BooleanField(default=False)),
                ('has_keys', models.BooleanField(default=False)),
                ('has_all_tires', models.BooleanField(default=False)),
                ('body_damage', models.CharField(blank=True, default='None', max_length=100)),
                ('engine_issue', models.BooleanField(default=False)),
                ('transmission_issue', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('zip_code', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('new', 'New'), ('evaluating', 'Evaluating'), ('offer_sent', 'Offer Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle Submission',
                'verbose_name_plural': 'Vehicle Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
