# Generated by Django 5.0 on 2026-09-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_vehiclesubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclesubmission',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vehiclesubmission',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vehiclesubmission',
            name='starts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehiclesubmission',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vehiclesubmission',
            name='transportation_required',
            field=models.BooleanField(default=False),
        ),
    ]
