# Generated by Django 5.0 on 2026-10-01 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hollander', '0019_vendor_brands_vendor_images_vendor_services'),
        ('leads', '0015_vehiclesubmission_city_vehiclesubmission_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_unlocked', models.BooleanField(default=False, help_text='True when vendor has paid to see full contact info')),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('price_paid', models.DecimalField(blank=True, decimal_places=2, help_text='USD amount collected to unlock this lead', max_digits=8, null=True)),
                ('teaser_email_sent', models.BooleanField(default=False, help_text="Whether the 'new lead assigned' teaser email was sent")),
                ('teaser_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Admin user who assigned this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_distributions_assigned', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='leads.lead')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_distributions', to='hollander.vendor')),
            ],
            options={
                'verbose_name': 'Lead Distribution',
                'verbose_name_plural': 'Lead Distributions',
                'ordering': ['-assigned_at'],
                'unique_together': {('lead', 'vendor')},
            },
        ),
    ]
