#!/usr/bin/env python3
"""
generate_nginx_redirects.py
============================
Generates /etc/nginx/jynm_redirects.conf (Nginx rewrite rules)
from the project's redirect_map.csv.

Usage:
    python3 scripts/generate_nginx_redirects.py
    # Then review /tmp/jynm_redirects.conf and copy to /etc/nginx/

The output file is an Nginx map + server block snippet that should be
included inside the main server block in junkyardsnearme.conf.
"""

import csv
import os
import sys
from urllib.parse import urlparse

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CSV_PATH  = os.path.join(REPO_ROOT, 'redirect_map.csv')
OUT_PATH  = '/tmp/jynm_redirects.conf'

def normalize(url: str, base_domain: str = 'junkyardsnearme.com') -> str:
    """Extract just the path from a URL, stripping query strings and trailing slashes."""
    url = url.strip()
    if url.startswith('http'):
        parsed = urlparse(url)
        path = parsed.path
    else:
        path = url if url.startswith('/') else '/' + url
    # Normalize: lowercase, strip trailing slash (except root)
    path = path.rstrip('/') or '/'
    return path.lower()


def main():
    if not os.path.exists(CSV_PATH):
        print(f'ERROR: {CSV_PATH} not found.', file=sys.stderr)
        sys.exit(1)

    redirects = {}
    skipped = 0

    with open(CSV_PATH, encoding='utf-8-sig') as f:
        # Auto-detect delimiter
        sample = f.read(2048)
        f.seek(0)
        delimiter = '\t' if '\t' in sample else ','
        reader = csv.DictReader(f, delimiter=delimiter)

        # Try common column name variations
        for i, row in enumerate(reader):
            keys = list(row.keys())
            # Detect old/new URL columns
            old_col = next((k for k in keys if 'old' in k.lower() or 'source' in k.lower() or 'from' in k.lower()), keys[0] if keys else None)
            new_col = next((k for k in keys if 'new' in k.lower() or 'dest' in k.lower() or 'target' in k.lower() or 'to' in k.lower()), keys[1] if len(keys) > 1 else None)

            if not old_col or not new_col:
                skipped += 1
                continue

            old_url = row.get(old_col, '').strip()
            new_url = row.get(new_col, '').strip()

            if not old_url or not new_url or old_url == new_url:
                skipped += 1
                continue

            old_path = normalize(old_url)
            new_path = normalize(new_url)

            if old_path == new_path or not old_path or not new_path:
                skipped += 1
                continue

            # Only keep first mapping for any old path (avoid duplicates)
            if old_path not in redirects:
                redirects[old_path] = new_path

    if not redirects:
        print('WARNING: No redirects found in CSV. Check column names.', file=sys.stderr)
        sys.exit(1)

    # Write Nginx config snippet (exact location blocks for common URLs,
    # plus a catch-all map for the bulk)
    lines = [
        '# Auto-generated JYNM legacy 301 redirects',
        f'# Source: redirect_map.csv  ({len(redirects)} rules)',
        '# Generated by: scripts/generate_nginx_redirects.py',
        '# Include this inside the main server block in junkyardsnearme.conf',
        '',
        '# ── Legacy URL 301 Redirects ─────────────────────────────────────────',
    ]

    for old_path, new_path in sorted(redirects.items()):
        # Escape special Nginx characters in paths
        safe_old = old_path.replace('$', '\\$')
        safe_new = new_path.replace('$', '\\$')
        lines.append(f'location = {safe_old} {{ return 301 {safe_new}; }}')

    output = '\n'.join(lines) + '\n'

    with open(OUT_PATH, 'w', encoding='utf-8') as f:
        f.write(output)

    print(f'✓ Generated {len(redirects)} redirects → {OUT_PATH}')
    print(f'  Skipped {skipped} invalid/identical rows')
    print()
    print('To deploy:')
    print(f'  sudo cp {OUT_PATH} /etc/nginx/jynm_redirects.conf')
    print('  Then uncomment the "include" line in nginx/junkyardsnearme.conf')
    print('  sudo nginx -t && sudo systemctl reload nginx')


if __name__ == '__main__':
    main()
