# Generated by Django 5.0 on 2026-07-29 05:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hollander', '0019_vendor_brands_vendor_images_vendor_services'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('billing_address', models.TextField(blank=True, default='')),
                ('line_items', models.JSONField(default=list, help_text='[{description, quantity, unit_price, total}]')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pdf_url', models.URLField(blank=True, help_text='URL to generated PDF if available', null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payment_invoices',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLifecycleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('note', models.TextField(blank=True, default='')),
                ('actor_email', models.CharField(default='system', help_text='Who caused this transition', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, help_text='Extra context at transition time', null=True)),
            ],
            options={
                'db_table': 'payment_transaction_lifecycle',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(help_text='Unique event ID from the gateway (deduplication key)', max_length=255, unique=True)),
                ('gateway', models.CharField(default='authorizenet', max_length=50)),
                ('event_type', models.CharField(blank=True, default='', max_length=100)),
                ('raw_payload', models.JSONField(help_text='Full raw payload from gateway')),
                ('signature_header', models.TextField(blank=True, default='', help_text='Raw X-ANET-Signature or equivalent header')),
                ('status', models.CharField(choices=[('received', 'Received'), ('verified', 'Signature Verified'), ('processed', 'Processed'), ('invalid_sig', 'Invalid Signature'), ('duplicate', 'Duplicate — Ignored'), ('failed', 'Processing Failed')], default='received', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_detail', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'payment_webhook_events',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='transaction',
            name='business_purpose',
            field=models.CharField(blank=True, default='', help_text='Human-readable description of what was purchased', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='correlation_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for cross-system tracing', unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='gateway',
            field=models.CharField(default='authorizenet', help_text='Which payment provider was used', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, help_text='Client-supplied key to prevent duplicate charges', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount refunded to date', max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='related_transaction',
            field=models.ForeignKey(blank=True, help_text='If this is a refund/void, link to original', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='payments.transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='risk_score',
            field=models.IntegerField(default=0, help_text='0-100 estimated risk. 0 = low.'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_module',
            field=models.CharField(blank=True, choices=[('vendor_ads', 'Vendor Ad Subscription'), ('yard_submission', 'Yard Submission Plan'), ('manual', 'Manual / Admin')], default='', help_text='Which UI module originated this payment', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='hollander.vendor'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='webhook_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='webhook_status',
            field=models.CharField(blank=True, default='not_expected', help_text='not_expected | pending | received | verified | failed', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='full_response',
            field=models.JSONField(blank=True, help_text='Full raw gateway response for audit', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('gateway_request_sent', 'Gateway Request Sent'), ('gateway_accepted', 'Gateway Accepted'), ('authorized', 'Authorized'), ('awaiting_webhook', 'Awaiting Webhook Verification'), ('webhook_received', 'Webhook Received'), ('signature_verified', 'Signature Verified'), ('captured', 'Captured'), ('completed', 'Completed'), ('failed', 'Failed'), ('voided', 'Voided'), ('refunded', 'Refunded'), ('partial_refund', 'Partial Refund'), ('chargeback', 'Chargeback'), ('archived', 'Archived')], db_index=True, default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Gateway transaction ID (e.g. Authorize.net transId)', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', '-created_at'], name='payment_tra_status_3d4a63_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-created_at'], name='payment_tra_user_id_001d5d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['vendor', '-created_at'], name='payment_tra_vendor__7f79e1_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_id'], name='payment_tra_transac_4a22d3_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['correlation_id'], name='payment_tra_correla_59c3c0_idx'),
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='payment_transactions',
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='payments.transaction'),
        ),
        migrations.AddField(
            model_name='transactionlifecyclelog',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_logs', to='payments.transaction'),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='payments.transaction'),
        ),
    ]
